Clinical-Genomics/MIP

dbParser.pl

Hej,
I figured I share the changes I made to dbParsel.pl.
It seems I have 'fixed' the indenting for me to work easier with the file. Feel free to just cherry pick the other commits and skip that one.
/Kenny

Exit code, error printing and bug fix

---

lib/MIP/Gnu/Coreutils.pm
t/config/run_test_files.txt
t/gnu_printf.t

print to stdoutfile_path was not implemented in gnu_printf

test for gnu_printf and minor corection of gnu_printf

---

templates/code/Command_module.pm

Created a template for generic MIP modules

Command module template

---

lib/MIP/Recipes/Sambamba_depth.pm
mip.pl

Sambamba depth recipe

---

templates/code/Command_module.pm

Removed some redundant modules. These are not needed if the module is used as intended, in conjunction with recipe/master script).  Feel free to reject if you think that they are needed for other reasons :)

small changes to command module template

---

lib/MIP/Log/MIP_log4perl.pm

Suggestion to color the log's screen output for log messages with levels higher than info

Added color to MIP's screen log

---

lib/MIP/Program/Variantcalling/SnpEff.pm
t/snpeff_download.t

discovered an error in snpeff_download while looking at fixing travis

small fix to snpeff_download

---

definitions/install_parameters.yaml
lib/MIP/Recipes/Install/Vcf2cytosure.pm
mip_install.pl

It works, the problem was the conda environment name, that on my computer is "base" instead of "root".

modified mip install to include vcf2cytosure installation

---

lib/MIP/Program/Trimming/Cutadapt.pm
t/cutadapt.t

- input fixed
- variables fixed
- paired end option added
- test module updated accordingly to changes above

Cutadapt.pm updated

---

lib/MIP/Program/Alignment/Star.pm
t/config/run_test_files.txt
t/star_genome_generate.t

Howdie!
I have made a test file for star genome generate (i.e to generate the index). 
//Jesper

Test for STAR GenomeGenerate

---

lib/MIP/Recipes/Install/Vep.pm

My git clone has stopped working again so I haven't been able to test it. Should work though

Now linking to environment specific library

---

lib/MIP/Program/Alignment/Picardtools.pm
lib/MIP/Recipes/Analysis/Star_aln.pm

Hello there!
Here's my first try of adding a readgroup to the star bam file.
By the way, how did you generate the slurm output file from running a recipie?
By the way, we need to index the bam file also! I forgot about that =P
//JEsper

Picard tools AddOrReplaceReadGroup

---

lib/MIP/Program/Variantcalling/Star_fusion.pm
t/star_fusion.t

Hello there!
I just made the module and test for star fusion

test and module for star fusion

---

lib/MIP/Program/Variantcalling/Salmon.pm
t/salmon_index.t
t/salmon_quant.t

Hello there!
I have made test and modules for the salmon software. Salmon is a tool for transcript quantification:
https://combine-lab.github.io/salmon/

Salmon test and modules

---

lib/MIP/Recipes/Analysis/Star_aln.pm

Godagens!
I tested running the RNA pipeline on Rasta. 
Star adds some stuff to the prefix of the output bam, so I needed to add those things to the input of Picard tools.
But now it works perfect!

IT'S ALIVE!

---

lib/MIP/Recipes/Pipeline/Rare_disease.pm

Of course I managed to break the rare_disease pipeline. Should be fixed now...

fixed broken rare_disease pipeline

---

lib/MIP/Main/Install.pm
lib/MIP/Package_manager/Conda.pm
lib/MIP/Recipes/Install/Conda.pm
t/conda_create.t
t/conda_install.t

Added conda-forge as a channel when installing bioconda packages

added codna-forge, fix #366 and fix #448

---

lib/MIP/Program/Alignment/Gatk.pm
t/gatk_splitncigarreads.t

There are many aligners! All with different properties, but which one represents you the most?
Begin the test by clicking the Merge button!
********
I made a test and module for GATK splitNcigarreads. This GATK tools split read containing N cigar operation into multiple alignment, also it changes the mapping qualities from 255 to 60.
This software should be run on the bam file before running variant calling and ASE analysis.

Develop: Which Aligner Are you?

---

lib/MIP/Recipes/Pipeline/Rna.pm

Removed indel realigner from the RNA pipeline

---

lib/MIP/Program/Variantcalling/BlobFish.pm
t/blobfish_all_vs_all.t

Blobfish is a wrapper around deseq2. Blobfish accepts a bunch of salmon quant.sf files and  produces all vs all comparisons for each setting/sample.
Visit this page to learn more about BlobFish:
https://www.smithsonianmag.com/science-nature/behold-the-blobfish-180956967/

The beutiful blobfish

---

lib/MIP/Program/Variantcalling/Bcftools.pm
lib/MIP/Recipes/Analysis/Gatk_combinevariantcallsets.pm
lib/MIP/Recipes/Analysis/Gatk_concatenate_genotypegvcfs.pm
lib/MIP/Recipes/Analysis/Sv_combinevariantcallsets.pm

Same changes as those that were pushed to the master branch earlier

removed .gz extension for compressed bcf files

---

definitions/install_rna_parameters.yaml
lib/MIP/Cli/Mip/Install/Rna.pm

Since we're going the cufflinks route I have removed trinity from the installation. Cufflinks is already part of the installation

removed trinity from the installation

---

definitions/cpanfile
definitions/install_rare_disease_parameters.yaml
definitions/install_rna_parameters.yaml
lib/MIP/Check/Installation.pm
lib/MIP/Get/Parameter.pm
lib/MIP/Main/Install.pm
lib/MIP/Package_manager/Conda.pm
lib/MIP/Set/Parameter.pm
t/check_and_add_dependencies.t
t/conda_install.t
t/get_programs_for_shell_installation.t
t/set_programs_for_installation.t

Some changes to the installation:  
- Shell programs that have their conda dependencies listed in the yaml file instead of the script
- Refactoring of code 
- Tests added

Moved dependencies, added tests and refactored

---

.travis.yml
README.md
definitions/install_rare_disease_parameters.yaml
documentation/README.md
lib/MIP/Cli/Mip/Install/Rare_disease.pm
t/mip_install.test

Freebayes has been separated from MIP's main environment due the new perl dependency

new freebayes env , Fix #537

---

lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Analysis/Gatk_haplotypecaller.pm
lib/MIP/Recipes/Analysis/Gatk_splitncigarreads.pm
lib/MIP/Recipes/Pipeline/Rna.pm

The rna pipeline now runs the same sub as the rare_disease pipeline. Will continue to update the haplotypecaller recipe.

io hash for gatk haplotypecaller

---

definitions/download_rd_rna_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Recipes/Analysis/Blobfish.pm
lib/MIP/Recipes/Build/Fusion_filter_prerequisites.pm
lib/MIP/Recipes/Build/Salmon_quant_prerequisites.pm
lib/MIP/Recipes/Build/Star_prerequisites.pm

Download transcript annotation file from Gencode. 
All rd_rna recipes that requires a gtf file now uses the same.

download gencode gtf

---

.travis.yml
definitions/install_rd_rna_parameters.yaml

Seems to be some issue with the most recent bioconda release of DeSeq2 (v1.20). Downgraded to 1.18.1

solve rna installation issue, fixes #651

---

definitions/analyse_parameters.yaml
definitions/install_rd_rna_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Get/Parameter.pm
lib/MIP/Program/Variantcalling/Salmon.pm
lib/MIP/QC/Sample_info.pm
lib/MIP/Recipes/Analysis/BootstrapAnn.pm
lib/MIP/Recipes/Analysis/Gatk_asereadcounter.pm
lib/MIP/Recipes/Analysis/Gatk_variantfiltration.pm
lib/MIP/Recipes/Analysis/Genebody_coverage.pm
lib/MIP/Recipes/Analysis/Gffcompare.pm
lib/MIP/Recipes/Analysis/Salmon_quant.pm
lib/MIP/Recipes/Analysis/Vep.pm
lib/MIP/Recipes/Pipeline/Rd_rna.pm
t/get_sequence_run_type.t
t/salmon_quant.t

- Add analysisrunstatus to RNA pipe
- Fix for running salmon quant on multi lane samples
- Changes some of the paths that are written to qc_sample_info
Will move the single-end/paired-end check in a later pull request

fix(RNA-pipe): Fixes to the Rd_rna pipeline

---

definitions/install_parameters.yaml
lib/MIP/Recipes/Install/Svdb.pm
lib/MIP/Recipes/Install/Vcf2cytosure.pm
mip_install.pl

- updated installation of svdb and vcf2cytosure
- added libstdcxx-ng dependeny in order to get the R part of picardtools collectmultiplemetrics to work
- added gatk dependency to cnvnator

fix(installation): master installation on hasta

---

definitions/define_parameters.yaml
lib/MIP/Program/Variantcalling/Vcf2cytosure.pm
lib/MIP/Recipes/Analysis/Vcf2cytosure.pm
mip.pl
t/vcf2cytosure.t

- added vcf2cytosure option --sex to recipe and command
- added vcf2cytosure option --maxbnd to recipe and command

feat(vcf2cytosure): new options for vcf2cytosure

---

lib/MIP/Recipes/Analysis/Vcf2cytosure.pm

Made vcf2cytosure variant size an option that you can set from command line or config

feat(vcf2cytosure): vcf2cytosure_var_size

---

lib/MIP/Recipes/Analysis/Vcf2cytosure.pm

Vcf2cytosure's size option can now be set from the config or command line

feat(vcf2cytosure): vcf2cytosre_var_size

---

documentation/API/Sample_info.md
lib/MIP/Get/Parameter.pm
lib/MIP/QC/Sample_info.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
lib/MIP/Set/Analysis.pm
t/analysis_run_bwa_mem.t
t/get_read_group.t
t/get_sequence_run_type_is_interleaved.t
t/set_recipe_bwa_mem.t

- Split bwa mem recipe for "bwa mem" and "run-bwa mem" into 2
independent recipes
- Depending on genome version either of the recipes will be initilized
- Moved get_read_group to sample_info.pm
- Created sub for getting interleaved status from sample_info hash
- Added use of get_sequencing_run_type to star aln recipe
- Added methods docs in API for Sample_info

feat(bwa_mem): Refactored bwa mem recipe

---

definitions/download_parameters.yaml
lib/MIP/Cli/Mip/Download.pm
lib/MIP/Main/Download.pm
lib/MIP/Recipes/Download/1000g_all_sv.pm
lib/MIP/Recipes/Download/1000g_all_wgs.pm
lib/MIP/Recipes/Download/1000g_indels.pm
lib/MIP/Recipes/Download/1000g_omni.pm
lib/MIP/Recipes/Download/1000g_sites.pm
lib/MIP/Recipes/Download/1000g_snps.pm
lib/MIP/Recipes/Download/Clinvar.pm
lib/MIP/Recipes/Download/Ctat_resource_lib.pm
lib/MIP/Recipes/Download/Dbnsfp.pm
lib/MIP/Recipes/Download/Dbsnp.pm
lib/MIP/Recipes/Download/Gencode_annotation.pm
lib/MIP/Recipes/Download/Genomic_superdups.pm
lib/MIP/Recipes/Download/Giab.pm
lib/MIP/Recipes/Download/Gnomad.pm
lib/MIP/Recipes/Download/Hapmap.pm
lib/MIP/Recipes/Download/Human_reference.pm
lib/MIP/Recipes/Download/Mills_and_1000g_indels.pm
lib/MIP/Recipes/Pipeline/Download_rd_dna.pm
lib/MIP/Recipes/Pipeline/Download_rd_rna.pm
lib/MIP/Script/Setup_script.pm
t/mip_download_rd_dna.test
t/mip_download_rd_rna.test
templates/code/recipe_download.pm
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml

- Removed cli sbatch_mode option as this is now implicit
- Updated some references and removed others
- Refactored main/download and pipeline/download

feat(remove_bash_download): Removed option to use download in batch mode

---

definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Markduplicates.pm
lib/MIP/Recipes/Analysis/Picardtools_mergesamfiles.pm
lib/MIP/Recipes/Analysis/Sv_reformat.pm

- Increased JAVA_GUEST_OS_MEMORY to 4G
- Modified memory and time allocation for recipes linked to vcf_rerun

fix(memory_update): Updates mermory parameters

---

definitions/install_rd_rna_parameters.yaml
definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Program/Alignment/Star.pm
lib/MIP/Program/Trimming/Trim_galore.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Analysis/Trim_galore.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_trim_galore.t
t/star_aln.t
t/trim_galore.t
templates/mip_rd_rna_config.yaml

- Adds option to trim RNA seq reads using trim galore
- Before aligning star tries to merge reads that overlap by more than 10 bases

feat(trim_&_star_aln): Add trim and star option

---

definitions/rd_dna_parameters.yaml
lib/MIP/Recipes/Analysis/Gatk_genotypegvcfs.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
mip-check

- Allow emptry string out tag vcf keys with svdb
- Fixed contig specific genomicsdb to prevent collisions

fix(svdb and gatk): Modified svdb and gatk recipe

---

lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
t/analysis_sv_annotate.t

0.40
- Updated test for recipe
- Updated vcf_rerun config

feat(filter svs): Added filtering of SVs with frequency greather than

---

definitions/rd_dna_parameters.yaml

feat(processing): Modifed core number for recipes using xargs to use 13

---

definitions/install_rd_dna_parameters.yaml
definitions/install_rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Install/Rd_rna.pm
lib/MIP/Main/Install.pm
lib/MIP/Program/Utility/Gtf2bed.pm
lib/MIP/Recipes/Download/Gencode_annotation.pm
lib/MIP/Recipes/Install/Gtf2bed.pm
t/gtf2bed.t
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml

Convert gtf to bed12 format for rseqc genebody coverage

feat(gtf2bed): convert gtf to bed12

---

definitions/download_rd_dna_parameters.yaml
lib/MIP/Recipes/Download/Gatk_mitochondrial_ref.pm
lib/MIP/Recipes/Pipeline/Download_rd_dna.pm
t/data/test_data/download_active_parameters.yaml
t/download_gatk_mitochondrial_ref.t
templates/mip_download_rd_dna_config_-1.0-.yaml

Download references for mitochondrial snv calling with mutect2 #742

feat(m_ref): download mitochondrial references

---

lib/MIP/Program/Dragen.pm
t/dragen_build_hash_table.t
t/dragen_dna_analysis.t

feat(dragen): Added dragen dna analysis cmd for end-to-end solution

---

definitions/download_rd_dna_parameters.yaml
lib/MIP/Recipes/Download/Genbank_haplogroup.pm
lib/MIP/Recipes/Download/Rank_model.pm
lib/MIP/Recipes/Download/Svrank_model.pm
lib/MIP/Recipes/Pipeline/Download_rd_dna.pm
t/data/test_data/download_active_parameters.yaml
t/download_genbank_haplogroup.t
t/download_rank_model.t
t/download_svrank_model.t
templates/mip_download_rd_dna_config_-1.0-.yaml

-  #829
- Manual download of files via mip dowload
- Mip downloads files without errors and with correct md5sum

feat(download): Added genbank_haplogroup, and rank models

---

documentation/References.md
documentation/Setup.md

docs(references): Describe private references in docs. Fix #832.

---

.travis.yml
README.md
definitions/install_rd_dna_parameters.yaml
definitions/install_rd_rna_parameters.yaml
documentation/README.md
lib/MIP/Cli/Mip/Install/Rd_dna.pm
lib/MIP/Cli/Mip/Install/Rd_rna.pm
templates/mip_rd_dna_config.yaml
templates/mip_rd_rna_config.yaml

- #851 
- Changed name of perl environment from eperl_5.26 to eperl5
- Turned off Snpeff installation for speedier testing 

fix(installation_test): Fixes #851

---

lib/MIP/Qc_data.pm
qccollect.pl
t/parse_regexp_hash_and_collect.t

- Added test
- Continued refactoring of qccollect

feat(qccollect): Moved parse_regexp_hash_and_collect to qc_data.pm

---

lib/MIP/Program/Download/Wget.pm
lib/MIP/Recipes/Download/Get_reference.pm
t/wget.t
templates/mip_download_rd_dna_config_-1.0-.yaml

to the bundle again. Fix  #867.
- #867 

feat(download): Add user to GATK bundle download scripts to get access

---

lib/MIP/Vcfparser.pm
t/build_interval_tree.t
templates/code/test.t
vcfparser.pl

- Added test
- Refactoring of feature_annotations sub

feat(vcfparser): Refactor feature_annotations in vcfparser

---

.github/CODEOWNERS
CONTRIBUTING.md

Codeowners

---

templates/mip_rd_dna_config.yaml

Fixes indentation for vep_custom_annotation

fix(mip_config_template): fixes indentation

---

lib/MIP/Vcfparser.pm
t/define_snpeff_annotations.t
vcfparser.pl

- Added test
- Moves snpeff annotations to separate pm and adds test

feat(vcfparser): Refactor define snpeff annotations

---

lib/MIP/Recipes/Download/Gnomad.pm

feat(download_gnomad_index): Fixed incorrect tabix command

---

lib/MIP/Vcfparser.pm
t/parse_consequence.t
vcfparser.pl

- Added test
- Refactoring of parsing of collected consequences

feat(vcfparser): Moved parsing of collected consequence to seperate sub

---

lib/MIP/Check/Installation.pm
t/check_existing_installation.t

feat(test): check_existing_installation

---

lib/MIP/Vcfparser.pm
t/parse_consequence.t
t/parse_vep_csq_transcripts.t
vcfparser.pl

feat(vcfparser): Refactored get annotation from VEP CSQ record

---

lib/MIP/Check/Installation.pm
t/check_python_compability.t

- Fixes python 3 compatibility test

feat(test): py3 compability test

---

lib/MIP/Vcfparser.pm
t/parse_vep_csq.t
vcfparser.pl

- Added test
- Refactor of parse_vep_csq

feat(vcfparser): Refactored parse_vep_csq

---

.travis.yml
CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Program/Mip.pm
t/mip_qccollect.t

fix(qc_collect): fixes skip_evaluation option

---

lib/MIP/Program/Mip.pm
t/mip_qccollect.t

fix(skip_evaluation): fixes qc_collect skip_evaluation

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Program/Alignment/Bedtools.pm
lib/MIP/Recipes/Analysis/Samtools_subsample_mt.pm
t/bedtools_genomecov.t

- A bug in downsampling of MT bam files

Subsample mt mast

---

CHANGELOG.md
definitions/install_rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Install/Rd_dna.pm
lib/MIP/Program/Chromograph.pm
lib/MIP/Program/Rhocall.pm
lib/MIP/Program/Upd.pm
lib/MIP/Recipes/Analysis/Rhocall.pm
lib/MIP/Recipes/Install/Chromograph.pm
lib/MIP/Recipes/Install/Rhocall.pm
lib/MIP/Recipes/Install/Upd.pm
lib/MIP/Recipes/Pipeline/Install_rd_dna.pm
t/chromograph_roh.t
t/chromograph_upd.t
t/rhocall_annotate.t
t/rhocall_viz.t
t/upd_call.t
templates/mip_install_rd_dna_config_-1.0-.yaml
templates/program_test_cmds.yaml

- installs upd and chromograph
- update rhocall version
- commands and tests for chromograph, upd and rhocall_viz
- part of #905

feat(chromograph): fix_prereq

---

lib/MIP/Vcfparser.pm
t/write_info_addition_fields.t
vcfparser.pl

- Added tests
- Refactor of writing additional INFO fields 

feat(vcfparser): Refactor write info addition fields

---

README.md
documentation/README.md

feat(doc): updates documentation

---

t/check_pip_package.t

fix(test): check_pip_package

---

CHANGELOG.md
definitions/rd_dna_parameters.yaml
lib/MIP/Constants.pm

- Increase memory for sv_varianteffectpredictior

Sv varianteff mem

---

definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml

parameter
- Increase mem for sv_varianeff

feat(sv_varianteff_mem): Increased mem from 8 to 9 Gb for recipe

---

CHANGELOG.md
definitions/dragen_rd_dna_parameters.yaml
definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
lib/MIP/Check/Reference.pm
lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Parse/Parameter.pm
lib/MIP/Program/Base/Bcftools.pm
lib/MIP/Program/Variantcalling/Bcftools.pm
lib/MIP/Recipes/Analysis/Frequency_annotation.pm
lib/MIP/Recipes/Analysis/Frequency_filter.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
t/analysis_frequency_annotation.t
t/analysis_frequency_filter.t
t/bcftools_base.t
t/check_references_for_vt.t
t/check_vcfanno_toml.t
t/mip_analyse_dragen_rd_dna.test
t/mip_analyse_rd_dna.test
t/mip_analyse_rd_dna_vcf_rerun.test
t/mip_analysis.test
t/parse_toml_config_parameters.t
templates/code/recipe_analysis_case.pm
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

- moves frequency annotation to separate recipe
- part of #905 

feat(frq_anno): splits recipe

---

t/check_references_for_vt.t

- Update test to enable toml testing again

test(fqa_vcfanno_config): Updated to enable toml testing again

---

CHANGELOG.md
definitions/dragen_rd_dna_initiation_map.yaml
definitions/dragen_rd_dna_parameters.yaml
definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_initiation_map.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
documentation/API/Sample_info.md
lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Program/Rhocall.pm
lib/MIP/Program/Upd.pm
lib/MIP/Program/Variantcalling/Bcftools.pm
lib/MIP/Recipes/Analysis/Rhocall.pm
lib/MIP/Recipes/Analysis/Upd.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
lib/MIP/Sample_info.pm
lib/MIP/Set/Analysis.pm
t/analysis_rhocall_viz.t
t/analysis_upd.t
t/bcftools_roh.t
t/bcftools_view.t
t/get_family_member_id.t
t/rhocall_viz.t
t/upd_call.t
templates/code/recipe_analysis_sample.t
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

- Adds chromograph chain
- Adds upd for trios
- Adds rhocall viz
- part of #905

feat(chromograph): pre requirements

---

lib/MIP/Set/Parameter.pm
t/set_custom_default_to_active_parameter.t

test(set_parameter): Extended test and small refactoring

---

lib/MIP/Constants.pm
lib/MIP/Unix/Write_to_file.pm
t/unix_write_to_file.t

test(with_singularity): Small refactoring and extended test

---

lib/MIP/Vcfparser.pm

- Remove unused code after refactoring

feat(parse_vep_csq): Removed unused code

---

CHANGELOG.md
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(update_manta):

---

CHANGELOG.md
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(update_vcfanno):

---

lib/MIP/Recipes/Analysis/Expansionhunter.pm
t/analysis_expansionhunter.t

test(expansionhunter): Added utility sub and extended test

---

t/analysis_gatk_combinevariantcallsets.t

test(gatk_combine): Extended test

---

t/analysis_gatk_gathervcfs.t

test(gatk_gather): Modified test

---

t/analysis_vep.t

test(vep): Modified test

---

CHANGELOG.md
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(update_multiqc)

---

lib/MIP/Processmanagement/Slurm_processes.pm
lib/MIP/Test/Fixtures.pm
t/slurm_submit_job_case_id_dependency_add_to_sample.t

feat(case_to_sample): Fix #973.

---

definitions/rd_dna_parameters.yaml

feat(bcftools_mpileup): Switched on bcftools mpileup as default

---

definitions/rd_rna_parameters.yaml

fix(trim_galore): increase memory

---

lib/MIP/Recipes/Analysis/Mip_qccollect.pm

fix(qccollect_path): Added correct recipe name to qc_sample_info.yaml

---

lib/MIP/Program/Chromograph.pm
lib/MIP/Recipes/Analysis/Chromograph.pm
lib/MIP/Recipes/Analysis/Rhocall.pm
t/analysis_rhocall_viz.t
t/chromograph_roh.t
templates/mip_rd_dna_config.yaml

fix(chain_chromograph): fix io files

---

documentation/Code/Install/Adding_a_container.md
documentation/Code/Install/Adding_a_program.md
documentation/Code/Install/Adding_an_env.md
templates/singularity/singularity_template.def

feat(singularity): documentation and template

---

CHANGELOG.md
definitions/rd_dna_parameters.yaml
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Gatk_variantrecalibration.pm

fix(variantrecalibrator): use MQ annotation for SNV

---

definitions/rd_dna_parameters.yaml
lib/MIP/Recipes/Analysis/Gatk_variantrecalibration.pm

fix(variantrecalibration): MQ annotation for wgs

---

lib/MIP/Main/Analyse.pm
lib/MIP/Parse/Parameter.pm
t/parse_dynamic_config_parameters.t
t/update_dynamic_config_parameters.t

- Added parse sub
- Added tests
- See above

feat(update_dynamic_param): Before updating all other parameters

---

templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

feat(rm_lof_add_lofTool): Removes lof from plugin and adds lofTools

---

lib/MIP/Qcc_regexp.pm
lib/MIP/Sample_info.pm
t/get_sample_info_sample_recipe_attributes.t

- Modifed some regexp for version, but will try a different approach in
another PR
- See above

feat(qccollect): Added return of correct hash level

---

definitions/dragen_rd_dna_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml

- Fix sv_annotat -> sv_annotate
- Move cnvnator bins for travis

feat(small_fixes): Added missing "e" fo sv_annotate

---

definitions/download_rd_dna_parameters.yaml
lib/MIP/Recipes/Download/Fqa_vcfanno_config.pm
lib/MIP/Recipes/Pipeline/Download_rd_dna.pm
t/data/test_data/download_active_parameters.yaml
t/download_fqa_vcfanno_config.t
templates/mip_download_rd_dna_config_-1.0-.yaml

feat(toml_download): Added download of frequency annotaion config

---

lib/MIP/Delete/File.pm
lib/MIP/Delete/List.pm
t/delete_non_wes_contig.t

contig
- Updated test
- See above

feat(contigs): Limit mixed case contigs to wes contigs, i.e. remove mt

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Delete/List.pm
t/delete_non_wes_contig.t

well.
- Updated test
- See above

Limit mixed case to wes contigs

---

templates/qc_regexp_-v1.24-.yaml

: Add new qc_regexp file without binary versions regexps
- See above

feat(qc_regexp): Add new qc_regexp file without binary versions regexps

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm

expansionhunter and sambamba depth.
- See above

fix(smbamba_depth_index): Fix possible race condition between

---

lib/MIP/Recipes/Analysis/Vep.pm

feat(vep_custom_ann): Remove undef elements before joining list.

---

t/check_references_for_vt.t

test(check_reference_for_vt_hash): Enabeld test for hash again.

---

t/parse_sing_bind_paths.t

test(parse_sing_bind): Added test

---

lib/MIP/Program/Varg.pm
t/varg_compare.t

Add perl wrapper and test for https://github.com/adrosenbaum/varg

---

t/data/references/grch37_frequency_vcfanno_filter_config_-v1.0-.toml

test(toml_config): Extended test data with another mock file

---

lib/MIP/Recipes/Install/Conda.pm
t/install_conda_packages.t

test(install_conda_packages): Added test and small refactoring

---

lib/MIP/Check/Installation.pm
lib/MIP/Recipes/Install/Mip_scripts.pm
t/check_mip_executable.t

- Added test
- Adds small sub and tests
- Actually no changes in "check_and_add_dependencies", just ordered it AB

test(mip_scripts): Added check_mip_executable sub

---

lib/MIP/Recipes/Install/Pip.pm
t/install_pip_packages.t

fix(pip): remove option to install in conda main

---

lib/MIP/Recipes/Install/Post_installation.pm
t/check_program_installations.t

test(check_program_installation): Added test

---

t/mip_install.test

feat(install): update config test

---

.travis.yml
containers/Singularity.trim_galore-0.6.4
lib/MIP/Cli/Mip/Install/Rd_rna.pm
lib/MIP/Get/Executable.pm
lib/MIP/Program/Trimming/Trim_galore.pm
lib/MIP/Recipes/Analysis/Trim_galore.pm
lib/MIP/Recipes/Install/Vep.pm
t/trim_galore.t
templates/mip_install_rd_rna_config_-1.0-.yaml
templates/mip_rd_rna_config.yaml
templates/program_test_cmds.yaml

feat(trim_galore): updates trim_galore, adds sif

---

lib/MIP/Recipes/Install/Post_installation.pm
t/data/test_data/not_valid_config.yaml
t/update_config.t

- May mark the end of 2 year old journey.... 😄 

test(update_config): Added test

---

.travis.yml
CHANGELOG.md
containers/Singularity.stringtie-2.0.3
lib/MIP/Get/Executable.pm
templates/mip_download_rd_rna_config_-1.0-.yaml
templates/mip_install_rd_rna_config_-1.0-.yaml

- Updates stringtie and moves it from conda to singularity
- Updates gffcompare
Downloaded the precompiled binary instead of installing via conda. This saves roughly 100MB 

feat(stringtie): sif installation

---

lib/MIP/Recipes/Install/Singularity.pm
lib/MIP/Recipes/Install/Vep.pm
t/data/test_data/install_rd_rna_active_parameters.yaml
t/install_singularity.t

- The cache directory is now automatically bound to the singularity container via the proxy bin 

feat(vep): install

---

lib/MIP/Recipes/Install/Cadd.pm
t/install_cadd.t

feat(cadd_install): Removed $FORWARD_SLASH from bind path

---

lib/MIP/Gnu/Bash.pm
lib/MIP/Recipes/Install/Post_installation.pm
t/gnu_set.t
templates/mip_install_rd_dna_config_-1.0-.yaml
templates/mip_install_rd_rna_config_-1.0-.yaml

- Use bash flag set -e for install 

feat(install): error check

---

templates/mip_install_rd_dna_config_-1.0-.yaml

feat(multiqc_install): Use dockerhub directly to build sif

---

CHANGELOG.md
templates/mip_download_rd_dna_config_-1.0-.yaml

feat(clinvar_update): Updated clinvar to 20191013

---

lib/MIP/Recipes/Analysis/Markduplicates.pm
lib/MIP/Recipes/Analysis/Picardtools_mergesamfiles.pm
t/xargs.t

feat(picard_xargs): Moved java cli from xargs call

---

templates/mip_download_rd_dna_config_-1.0-.yaml

feat(gnomad_update): Added download of gnomad r2.1.1

---

lib/MIP/Program/Rtg.pm
lib/MIP/Recipes/Analysis/Rtg_vcfeval.pm
lib/MIP/Recipes/Download/Gnomad.pm
t/rtg_vcfeval.t
t/rtg_vcfsubset.t

feat(gnomad_post_processing): Added option to handle memory for rtg

---

lib/MIP/Get/Executable.pm

- new regex:s for RNA programs

feat(version_collect): new regex:s

---

definitions/rd_rna_parameters.yaml

feat(rna_config): updates parameters

---

lib/MIP/Program/Chanjo.pm
lib/MIP/Recipes/Analysis/Chanjo_sex_check.pm
t/chanjo_sex.t

feat(chanjo): Refactor and move up one dir

---

lib/MIP/Program/Sambamba.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm
lib/MIP/Recipes/Analysis/Markduplicates.pm
lib/MIP/Recipes/Analysis/Picardtools_mergesamfiles.pm
lib/MIP/Recipes/Analysis/Sambamba_depth.pm
t/sambamba_depth.t
t/sambamba_flagstat.t
t/sambamba_index.t
t/sambamba_markdup.t
t/sambamba_sort.t
t/sambamba_view.t

feat(sambama): Refactor and moce up one dir

---

lib/MIP/Program/Blast.pm
lib/MIP/Recipes/Build/Star_fusion_prerequisites.pm
t/blast_blastn.t
t/blast_makeblastdb.t

feat(blast): Refactor and move up one dir

---

templates/mip_install_rd_rna_config_-1.0-.yaml

feat(star_fusion): fusion build binaries

---

lib/MIP/Program/Samtools.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm
lib/MIP/Recipes/Analysis/Cnvnator.pm
lib/MIP/Recipes/Analysis/Picardtools_mergesamfiles.pm
lib/MIP/Recipes/Analysis/Samtools_subsample_mt.pm
lib/MIP/Recipes/Build/Human_genome_prerequisites.pm
t/samtools_create_chromosome_files.t
t/samtools_depth.t
t/samtools_faidx.t
t/samtools_idxstats.t
t/samtools_index.t
t/samtools_stats.t
t/samtools_view.t

feat(sambamba): Refactor and move up one dir

---

lib/MIP/Program/Gatk.pm
lib/MIP/Recipes/Analysis/Gatk_asereadcounter.pm
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Analysis/Gatk_haplotypecaller.pm
lib/MIP/Recipes/Analysis/Gatk_splitncigarreads.pm
t/gatk_applybqsr.t
t/gatk_asereadcounter.t
t/gatk_baserecalibrator.t
t/gatk_gatherbqsrreports.t
t/gatk_haplotypecaller.t
t/gatk_printreads.t
t/gatk_splitncigarreads.t

feat(gatk): Refactor and move up one dir

---

lib/MIP/Parse/Gender.pm
lib/MIP/Program/Bwa.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm
lib/MIP/Recipes/Build/Bwa_prerequisites.pm
t/bwa_index.t
t/bwa_mem.t
t/run_bwa.t

feat(bwa): Refactor and move up one dir

---

lib/MIP/Program/Star.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Build/Star_prerequisites.pm
t/star_aln.t
t/star_genome_generate.t

feat(star): Refactor and move up one dir

---

definitions/rd_rna_parameters.yaml
lib/MIP/Get/Executable.pm
lib/MIP/Recipes/Analysis/Multiqc.pm

- multiqc memory
- updated program version regexp

feat(small_fixes)

---

lib/MIP/Program/Bzip2.pm
t/bzip2.t

feat(bzip2): Refactor and move up one dir

---

lib/MIP/Program/Pigz.pm
lib/MIP/Recipes/Analysis/Split_fastq_file.pm
t/pigz.t

feat(pigz): Refactor and move up one dir

---

definitions/rd_rna_parameters.yaml
lib/MIP/Recipes/Analysis/Trim_galore.pm

feat(trim_galore): fix bug in recipe

---

definitions/analyse_parameters.yaml
definitions/dragen_rd_dna_parameters.yaml
definitions/mip_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Recipes/Install/Mip_scripts.pm
t/data/references/qc_regexp_-v1.24-.yaml
t/mip_analyse_dragen_rd_dna.test
t/mip_analyse_rd_dna.test
t/mip_core.t
templates/grch38_mip_rd_dna_config.yaml
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml
templates/mip_rd_rna_config.yaml

- Added program_tests to mip_core
- Fixed missing reference path in dragen pipeline test
- Use imported sub instead of utility sub for vcf_rerun pipe test
- See above

feat(set_default): Moved some parameter settings from config to defaults

---

containers/Singularity.chromograph-0.1.2
templates/mip_install_rd_dna_config_-1.0-.yaml

- Fixes display issues when running on nodes
- Tested on hasta and it works

feat(chromograph): Updated sif to version 0.1.2

---

lib/MIP/Program/Wget.pm
lib/MIP/Recipes/Download/Get_reference.pm
lib/MIP/Recipes/Install/Gtf2bed.pm
lib/MIP/Recipes/Install/Vep.pm
t/wget.t
templates/code/recipe_install_shell.pm

feat(wget): Move up one dir

---

lib/MIP/Program/Multiqc.pm
lib/MIP/Recipes/Analysis/Multiqc.pm
t/multiqc.t

feat(multiqc): Refactor and move up one dir

---

documentation/API/Modules.md
lib/MIP/Program/Fastqc.pm
lib/MIP/Recipes/Analysis/Fastqc.pm
t/fastqc.t

feat(fastqc): Refactor and move up one dir

---

templates/mip_install_rd_dna_config_-1.0-.yaml

feat(bedtools_docker): Added docker to install

---

lib/MIP/Recipes/Install/Conda.pm
t/install_conda_packages.t

- creates new empty conda env if it doesn't exist and no conda pacakages
have been selected. Fixes #1174 

feat(install): create conda env

---

containers/bwa/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(bwa_docker): Added docker image and use it in install

---

lib/MIP/Program/Peddy.pm
lib/MIP/Recipes/Analysis/Peddy.pm
t/peddy.t

feat(peddy): Refactor and move up one dir

---

lib/MIP/Program/Preseq.pm
lib/MIP/Recipes/Analysis/Preseq.pm
t/preseq_lc_extrap.t

feat(preseq): Refactor and move up one dir

---

lib/MIP/Program/Variantcalling/Tiddit.pm
lib/MIP/Recipes/Analysis/Tiddit_coverage.pm
t/tiddit_coverage.t

- Adds -u option to tiddit coverage call, which removes the quality track in the wig file.
- Should fix #1182 

feat(tiddit_cov): added option -u

---

lib/MIP/Program/Rseqc.pm
lib/MIP/Recipes/Analysis/Genebody_coverage.pm
lib/MIP/Recipes/Analysis/Rseqc.pm
t/rseqc_bam2wig.t
t/rseqc_bam_stat.t
t/rseqc_genebody_coverage2.t
t/rseqc_infer_experiment.t
t/rseqc_inner_distance.t
t/rseqc_junction_annotation.t
t/rseqc_junction_saturation.t
t/rseqc_read_distribution.t
t/rseqc_read_duplication.t

feat(rseqc): Refactor and move up one dir

---

lib/MIP/Program/Gtf2bed.pm
lib/MIP/Recipes/Download/Gencode_annotation.pm
t/gtf2bed.t

feat(gtf2bed): Refactor and move up one dir

---

lib/MIP/Program/Trim_galore.pm
lib/MIP/Recipes/Analysis/Trim_galore.pm
t/trim_galore.t

feat(trim_galore): Refactor and move up one dir

---

lib/MIP/Program/Htslib.pm
lib/MIP/Recipes/Analysis/Cadd.pm
lib/MIP/Recipes/Analysis/Endvariantannotationblock.pm
lib/MIP/Recipes/Analysis/Prepareforvariantannotationblock.pm
lib/MIP/Recipes/Analysis/Vcf_rerun_reformat.pm
lib/MIP/Recipes/Analysis/Vep.pm
lib/MIP/Recipes/Analysis/Vt_core.pm
lib/MIP/Recipes/Download/Clinvar.pm
lib/MIP/Recipes/Download/Dbnsfp.pm
lib/MIP/Recipes/Download/Genomic_superdups.pm
lib/MIP/Recipes/Download/Gnomad.pm
t/htslib_bgzip.t
t/htslib_tabix.t

feat(htslib): Refactor and move up one dir

---

lib/MIP/Program/BootstrapAnn.pm
lib/MIP/Recipes/Analysis/BootstrapAnn.pm
t/bootstrapann.t

feat(bootstrapann): Refactor and move up one dir

---

lib/MIP/Program/Blobfish.pm
lib/MIP/Recipes/Analysis/Blobfish.pm
t/blobfish_allvsall.t

feat(blobfish): Refactor and move up one dir

---

lib/MIP/Program/Cnvnator.pm
lib/MIP/Recipes/Analysis/Cnvnator.pm
t/cnvnator_calling.t
t/cnvnator_convert_to_vcf.t
t/cnvnator_histogram.t
t/cnvnator_partition.t
t/cnvnator_read_extraction.t
t/cnvnator_statistics.t

feat(cnvnator): Refactor and move up one dir

---

lib/MIP/Program/Delly.pm
lib/MIP/Recipes/Analysis/Delly_call.pm
lib/MIP/Recipes/Analysis/Delly_reformat.pm
t/delly_call.t
t/delly_filter.t
t/delly_merge.t

feat(delly): Refactored and move up one dir

---

containers/htslib/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(htslib_docker): Added docker for htslib and use uri in mip install

---

containers/manta/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(manta_docker): Added manta docker and use uri in install

---

definitions/rd_dna_vcf_rerun_parameters.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

- Added picardtools_path
- Removes exists check on picard path as it is now in container
- Adds picard path in container to config

feat(rd_dna_vcf_rerun): Modifed config

---

containers/peddy/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(peddy_docker): Added docker and uri

---

lib/MIP/Program/Genmod.pm
lib/MIP/Recipes/Analysis/Rankvariant.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
t/genmod_annotate.t
t/genmod_compound.t
t/genmod_filter.t
t/genmod_models.t
t/genmod_score.t

feat(genmod): Refactor and move up one dir

---

lib/MIP/Program/Variantcalling/Genmod.pm
lib/MIP/Recipes/Analysis/Rankvariant.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
t/genmod_annotate.t
t/genmod_compound.t
t/genmod_filter.t
t/genmod_models.t
t/genmod_score.t

Reverts Clinical-Genomics/MIP#1205

Revert "feat(genmod): Refactor and move up one dir"

---

lib/MIP/Program/Genmod.pm

- Messed up the merging - redoing it again

feat(genmod): fixed according to comments

---

lib/MIP/Program/Expansionhunter.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
t/expansionhunter.t

feat(expansionhunter): Refactor and move up one dir

---

CHANGELOG.md

feat(update_changelog):

---

templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

ordinary snv/indel detection.
- See above

feat(gnomad_sv_annotate): Added new version of gnomad to SV part for

---

lib/MIP/Program/Perl.pm
lib/MIP/Recipes/Analysis/Bcftools_mpileup.pm
t/replace_iupac.t

feat(perl): Refactore and move up one dir

---

templates/mip_install_rd_dna_config_-1.0-.yaml

feat(picard_docker): Use docker uri in mip install instead of shub

---

containers/plink/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(plink_docker): Added plink docker and uri

---

containers/rhocall/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(rhocall_docker): Added docker and use uri

---

lib/MIP/Program/Genmod.pm
lib/MIP/Recipes/Analysis/Rankvariant.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
t/genmod_annotate.t
t/genmod_compound.t
t/genmod_filter.t
t/genmod_models.t
t/genmod_score.t

feat(genmod_again): Trying to get the changes in again after reverting

---

lib/MIP/Program/Gffcompare.pm
lib/MIP/Recipes/Analysis/Gffcompare.pm
t/gffcompare.t

feat(gff_compare): Refactor and move up one dir

---

lib/MIP/Program/Manta.pm
lib/MIP/Recipes/Analysis/Manta.pm
t/manta_config.t
t/manta_workflow.t

feat(manta): Refactore and move up one dir

---

containers/sambamba/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(sambamba_docker): Added docker and use uri in mip install

---

containers/stranger/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(stranger_docker): Added docker and use uri in mip install

---

lib/MIP/Program/Stranger.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
t/stranger.t

feat(stranger): Refactor and move up one dir

---

lib/MIP/Program/Salmon.pm
lib/MIP/Recipes/Analysis/Salmon_quant.pm
lib/MIP/Recipes/Build/Salmon_quant_prerequisites.pm
t/salmon_index.t
t/salmon_quant.t

feat(salmon): Refactor and move up one dir

---

lib/MIP/Program/Stringtie.pm
lib/MIP/Recipes/Analysis/Stringtie.pm
t/stringtie.t

feat(stringtie): Refactor and move up one dir

---

lib/MIP/Program/Svdb.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
lib/MIP/Recipes/Analysis/Sv_combinevariantcallsets.pm
lib/MIP/Recipes/Analysis/Tiddit.pm
t/svdb_merge.t
t/svdb_query.t

feat(svdb): Refactor and move up one dir

---

lib/MIP/Program/Plink.pm
lib/MIP/Recipes/Analysis/Plink.pm
t/plink_calculate_inbreeding.t
t/plink_check_sex_chroms.t
t/plink_create_mibs.t
t/plink_fix_fam_ped_map_freq.t
t/plink_sex_check.t
t/plink_variant_pruning.t

feat(plink): Refactor and move up one dir

---

containers/varg/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(varg_docker): Added varg docker and use uri in install

---

containers/variant_integrity/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(variant_integrity): Added docker and use uri in install

---

CHANGELOG.md
containers/stranger/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(stranger_update): Updated stranger via docker

---

containers/upd/Dockerfile
lib/MIP/Test/Fixtures.pm
t/test_standard_cli.t
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(upd_docker): Added docker and use uri in install

---

definitions/analyse_parameters.yaml
definitions/download_parameters.yaml
definitions/install_parameters.yaml
definitions/mip_parameters.yaml
definitions/non_mandatory_parameter_keys.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
definitions/rd_rna_parameters.yaml
documentation/API/define_parameters.md
t/data/test_data/define_parameters.yaml

- The key element_separator doesn't seem to be used anymore. 

feat(parameter_key): removes element_separator

---

lib/MIP/Program/Trinity.pm
t/trinity_genome_guided.t

feat(trinity): Refactor and move up one dir

---

lib/MIP/Program/Tiddit.pm
lib/MIP/Recipes/Analysis/Tiddit.pm
lib/MIP/Recipes/Analysis/Tiddit_coverage.pm
lib/MIP/Recipes/Analysis/Vcf2cytosure.pm
t/tiddit_coverage.t
t/tiddit_sv.t

feat(tiddit): Refactor and move up one dir

---

lib/MIP/Program/Variant_integrity.pm
lib/MIP/Recipes/Analysis/Variant_integrity.pm
t/variant_integrity_father.t
t/variant_integrity_mendel.t

feat(variant_integrity): Refactor and move up one dir

---

lib/MIP/Program/Vcf2cytosure.pm
lib/MIP/Recipes/Analysis/Vcf2cytosure.pm
t/vcf2cytosure.t

feat(vcf2cytosure): Refactor and move up one dir

---

containers/vcfanno/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(vcfanno_docker): Added docker and use uri in install

---

containers/vt/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

feat(vt_docker): Added docker and use uri in install

---

lib/MIP/Program/Vt.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
lib/MIP/Recipes/Analysis/Plink.pm
lib/MIP/Recipes/Analysis/Sv_combinevariantcallsets.pm
lib/MIP/Recipes/Analysis/Vt_core.pm
t/vt_decompose.t
t/vt_normalize.t
t/vt_uniq.t

feat(vt): Refactor and move up one dir

---

lib/MIP/Program/Vep.pm
lib/MIP/Recipes/Analysis/Vep.pm
lib/MIP/Recipes/Install/Vep.pm
t/variant_effect_predictor.t
t/variant_effect_predictor_install.t

feat(vep): Refactor and move up one dir

---

lib/MIP/Program/Vcfanno.pm
lib/MIP/Recipes/Analysis/Frequency_annotation.pm
lib/MIP/Recipes/Analysis/Sv_annotate.pm
t/vcfanno.t

feat(vcfanno): Refactor and move up one dir

---

definitions/rd_rna_parameters.yaml
lib/MIP/Program/Star.pm
lib/MIP/Recipes/Analysis/Star_aln.pm

feat(star_options): updates star parameters

---

lib/MIP/Gnu/Coreutils.pm
t/gnu_tee.t

feat(tee): adds tee command

---

.travis.yml
lib/MIP/Cli/Mip/Install/Rd_rna.pm
templates/mip_install_rd_rna_config_-1.0-.yaml
templates/program_test_cmds.yaml

feat(arriba): installation

---

lib/MIP/Program/Arriba.pm
t/arriba.t

feat(Arriba): command module

---

lib/MIP/Program/Arriba.pm
t/draw_fusions.t

feat(draw_fusions): command module

---

lib/MIP/Program/Star.pm
t/star_aln.t

- more star commands needed for arriba

feat(star_aln): more commands

---

definitions/rd_dna_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm

feat(gatk_bundle): Removed option as it is no longer used

---

lib/MIP/Parse/Reference.pm
lib/MIP/Recipes/Analysis/Vt_core.pm
t/analysis_vt_core.t

feat(gatk_index): Build gatk index after decomposing and normalising

---

definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Check/Parameter.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Get/Executable.pm
lib/MIP/Recipes/Analysis/Arriba.pm
lib/MIP/Recipes/Analysis/Star_fusion.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
lib/MIP/Set/Parameter.pm
t/analysis_arriba.t
t/check_recipe_fastq_compatibility.t
t/data/test_data/rd_rna_initiation_map.yaml
t/set_recipe_mode.t
templates/code/recipe_analysis_sample.pm
templates/mip_rd_rna_config.yaml

feat(arriba): recipe

---

definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Gnu/Bash.pm
lib/MIP/Recipes/Analysis/Arriba.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Analysis/Star_fusion.pm
lib/MIP/Script/Setup_script.pm
t/gnu_ulimit.t
t/setup_script.t

feat(star): set ulimit -n in star recipes

---

templates/mip_install_rd_dna_config_-1.0-.yaml
templates/mip_install_rd_rna_config_-1.0-.yaml

feat(vep): shub --> docker hub

---

templates/mip_install_rd_rna_config_-1.0-.yaml

feat(containers): shub --> docker hub

---

lib/MIP/Recipes/Analysis/Arriba.pm
lib/MIP/Recipes/Analysis/Bcftools_merge.pm
lib/MIP/Recipes/Analysis/Gffcompare.pm
lib/MIP/Recipes/Analysis/Markduplicates.pm
lib/MIP/Recipes/Analysis/Star_fusion.pm
lib/MIP/Recipes/Analysis/Stringtie.pm
lib/MIP/Recipes/Analysis/Vep.pm
t/analysis_markduplicates.t

feat(rna_store): store some rna files

---

README.md
documentation/Parameters.md
documentation/README.md
documentation/Recipes.md
documentation/Setup.md

docs(updated):

---

definitions/mip_install_perl.sh
lib/MIP/Constants.pm
lib/MIP/Recipes/Install/Post_installation.pm

feat(install): fixes install check error

---

lib/MIP/Main/Analyse.pm

feat(rm_chomp): Removed chomp as it is not needed

---

lib/MIP/Constants.pm

fix(rm_uc_ref): Remove upper case reference from test data

---

lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Get/Analysis.pm
lib/MIP/Parameter.pm
t/print_recipe.t

feat(print_recipe): Refactor and move to parameter.pm

---

lib/MIP/Cli/Mip/Analyse.pm
lib/MIP/Cli/Mip/Download/Rd_dna.pm
lib/MIP/Cli/Mip/Download/Rd_rna.pm
lib/MIP/Cli/Mip/Install.pm
lib/MIP/Cli/Mip/Install/Rd_dna.pm
lib/MIP/Cli/Mip/Install/Rd_rna.pm

feat(cli_imports): Removed unused imports

---

CHANGELOG.md
definitions/rd_dna_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Recipes/Analysis/Markduplicates.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_markduplicates_rna.t

- see above
- removes option to run sambamba markduplicates for RNA
- removes cli options linked to split

feat(md_rna): splits md recipe into dna/rna subs

---

definitions/rd_dna_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_gatk_baserecalibration_rna.t

feat(rna): separate baserecalibation recipe

---

CHANGELOG.md
lib/MIP/Check/Pipeline.pm

- Added to CHANGELOG
- See above

feat(SMNCopyNumberCaller): Turn it off when not wgs

---

definitions/rd_dna_parameters.yaml

discussion with CMMS
- See above

feat(samtools_subsample_mt_depth): Modifed default according to

---

lib/MIP/Constants.pm
lib/MIP/Recipes/Pipeline/Analyse_dragen_rd_dna.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_vcf_rerun.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/parse_sing_bind_paths.t
t/unix_write_to_file.t

feat(refactor): Renamed sub. Fix #1271

---

lib/MIP/Active_parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
lib/MIP/Main/Install.pm
lib/MIP/Parameter.pm
lib/MIP/Set/Parameter.pm
t/set_default_parameter.t
t/set_default_to_active_parameter.t

- Refactor set default to active parameter

feat(refactor): Refacored set_default_to_active_parameter

---

lib/MIP/Active_parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Set/Parameter.pm
lib/MIP/Update/Parameters.pm
t/set_parameter_reference_dir_path.t

- Small refactoring
- See above

feat(refactor): Moved sub

---

t/set_default.t

- Fixes test that sometimes fail if mandatory parameter is not set

feat(test): Reduce test to not exit if not mandatory file is set in test

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Path.pm
lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Dependency_tree.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
lib/MIP/Parameter.pm
t/check_parameter_files.t
t/get_cache.t
t/get_parameter_attribute.t
t/set_dependency_tree_order.t

- Refactor and created new get subs
- New sub for getting a cache parmeter value from parameter hash
- New sub for getting a parameter attribute hash from parameter hash
- Moved check_parameter_files to active_parameter module
- Use new subs and added new options to set_parameter_files

feat(check_parameter_files): Refactor and created new get subs

---

lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
lib/MIP/Parameter.pm
t/check_parameter_files.t
t/parse_parameter_files.t

feat(refactor): New sub parse_parameter_files

---

definitions/rd_rna_parameters.yaml
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml

- adds the reference genome parameters for star and salmon

feat(rna_ref): adds rna ref genomes

---

lib/MIP/Config.pm
lib/MIP/File/Format/Reference.pm
lib/MIP/File/Format/Yaml.pm
lib/MIP/Io/Write.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Main/Qccollect.pm
lib/MIP/Main/Vercollect.pm
lib/MIP/Processmanagement/Processes.pm
lib/MIP/Qcc_regexp.pm
lib/MIP/Recipes/Analysis/Mip_vercollect.pm
t/write_to_file.t

- Added yaml
- Added test
- See above

feat(write_to_file): Added control sub for writing to file

---

.travis.yml
containers/ucsc/Dockerfile
containers/wigtobigwig/Dockerfile
lib/MIP/Cli/Mip/Install/Rd_dna.pm
lib/MIP/Cli/Mip/Install/Rd_rna.pm
templates/mip_install_rd_dna_config_-1.0-.yaml
templates/mip_install_rd_rna_config_-1.0-.yaml

- Adds a docker for wigtobigwig

feat(wigtobigwig): Added docker. For Fix #1327

---

lib/MIP/Active_parameter.pm
lib/MIP/Cluster.pm
lib/MIP/Environment/Cluster.pm
lib/MIP/Get/Parameter.pm
lib/MIP/Main/Analyse.pm
t/check_recipe_memory_allocation.t

- Refactored sub check_recipe_memory_allocation
- See above

feat(recipe_resource): Set limit if required to recipe memory

---

lib/MIP/Get/Executable.pm
lib/MIP/Main/Vercollect.pm

- sets max heap memory for gatk when running versioncollect

fix(versioncollect): fixes mem error

---

lib/MIP/Environment/User.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
t/check_email_address.t

feat(Refactor): Moved sub check_email_adress

---

lib/MIP/Io/Read.pm
lib/MIP/Io/Write.pm
lib/MIP/Yaml.pm
t/load_yaml.t
t/write_yaml.t

feat(refactor): Moved module

---

lib/MIP/Active_parameter.pm
lib/MIP/Get/Parameter.pm
lib/MIP/Script/Setup_script.pm
t/get_package_env_attibutes.t

- Moved sub
- Reduced one level
- See above

feat(refactor): Get_package_env_attibutes

---

CHANGELOG.md
definitions/analyse_parameters.yaml
definitions/rd_dna_parameters.yaml
documentation/API/Pedigree.md
lib/MIP/Cli/Mip/Analyse.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Recipes/Analysis/Vcf2cytosure.pm
lib/MIP/Sample_info.pm
t/analysis_vcf2cytosure.t
t/get_pedigree_sample_id_attributes.t
templates/mip_install_rd_dna_config_-1.0-.yaml

- Get sample_display_name from pedigree
- Rename sample_id in vcf2cytosure input VCF to sample_display_name
- See above

feat(display_name): Added use of display name to MIP

---

documentation/API/Tests.md
lib/MIP/Environment/Manager.pm
lib/MIP/Program/Conda.pm
lib/MIP/Recipes/Install/Blobfish.pm
lib/MIP/Recipes/Install/BootstrapAnn.pm
lib/MIP/Recipes/Install/Conda.pm
lib/MIP/Recipes/Install/Gtf2bed.pm
lib/MIP/Recipes/Install/Pip.pm
lib/MIP/Script/Setup_script.pm
t/conda_activate.t
t/conda_create.t
t/conda_deactivate.t
t/conda_install.t
templates/code/recipe_install_shell.pm

feat(refactor): Moved conda to MIP::Program

---

.travis.yml
containers/preseq/Dockerfile
templates/mip_install_rd_rna_config_-1.0-.yaml

feat(preseq): docker installation

---

lib/MIP/Program/Pip.pm
lib/MIP/Recipes/Install/Pip.pm
t/pip_install.t

- Simply moved the module
- See above

feat(pip): Refactor pip

---

lib/MIP/Check/Parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Validate/Case.pm
t/check_sample_ids.t

feat(check_sample_ids): Refactor and move sub

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/File/Format/Store.pm
lib/MIP/Main/Analyse.pm
t/parse_store_files.t

- removes old duplicates from store hash

fix(store): removes old duplicates

---

lib/MIP/File/Format/Store.pm
lib/MIP/Main/Analyse.pm
t/parse_store_files.t

feat(store): remove old duplicates

---

lib/MIP/Get/Parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Parameter.pm
t/set_cache_program_executables.t

- Refactored get_program_executables
- Added test
- See above

feat(cache_executables): Added new sub for setting program_executables

---

lib/MIP/Program/Samtools.pm
t/samtools_base.t

- Use samtools_base in samtools_view
- Added test
- See above

feat(samtools): Added samtools_base, with write-index option. Fix #1353

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
lib/MIP/Parameter.pm
t/check_recipe_mode.t

feat(check_recipe_mode): Refactored

---

lib/MIP/Active_parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Parse/Parameter.pm
lib/MIP/Recipes/Parse.pm
lib/MIP/Update/Recipes.pm
mip-test-suite
t/parse_start_with_recipe.t
t/update_recipe_mode_for_start_with_option.t

- Added bash script to run test suite
- See above

feat(parse_start_with_recipe): Refactor

---

lib/MIP/Recipes/Analysis/Chromograph.pm

bedToBigBed exits if folder does not exist
- See above

feat(chromograph): Added creation of folder for tar archive since

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Parameter.pm
lib/MIP/Main/Analyse.pm
t/check_load_env_packages.t

feat(refactor): check_load_env_packages

---

lib/MIP/Active_parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Pedigree.pm
lib/MIP/Sample_info.pm
t/set_gender_sample_ids.t

feat(gender): Refactor

---

lib/MIP/Check/Parameter.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Parameter.pm
t/check_recipe_vs_binary_name.t

feat(check_recipe_name): Refactor and move sub

---

.travis.yml
containers/gffcompare/Dockerfile
templates/mip_install_rd_rna_config_-1.0-.yaml

- moves gffcompare to docker container

feat(gffcompare): docker version

---

.travis.yml
containers/salmon/Dockerfile
templates/mip_install_rd_rna_config_-1.0-.yaml

- moves salmon to docker container

feat(salmon): salmon container

---

containers/chromograph/Dockerfile
templates/mip_install_rd_dna_config_-1.0-.yaml

fix(chromograph): docker update

---

lib/MIP/Recipes/Parse.pm

feat(refactor): Use sub instead of traversing hash

---

lib/MIP/Main/Analyse.pm
lib/MIP/Processmanagement/Processes.pm
t/get_all_job_ids.t
t/write_job_ids_to_file.t

feat(refactor): write_job_ids_to_file

---

containers/Dockerfile
containers/bedtools/Dockerfile
containers/blobfish/Dockerfile
containers/bootstrapann/Dockerfile
containers/bwa/Dockerfile
containers/bwakit/Dockerfile
containers/chanjo/Dockerfile
containers/chromograph/Dockerfile
containers/expansionhunter/Dockerfile
containers/fastqc/Dockerfile
containers/genmod/Dockerfile
containers/gffcompare/Dockerfile
containers/htslib/Dockerfile
containers/manta/Dockerfile
containers/peddy/Dockerfile
containers/plink/Dockerfile
containers/preseq/Dockerfile
containers/rhocall/Dockerfile
containers/salmon/Dockerfile
containers/sambamba/Dockerfile
containers/smncopynumbercaller/Dockerfile
containers/stranger/Dockerfile
containers/ucsc/Dockerfile
containers/upd/Dockerfile
containers/utilities/Dockerfile
containers/varg/Dockerfile
containers/variant_integrity/Dockerfile
containers/vcfanno/Dockerfile
containers/vt/Dockerfile

feat(docker): Linting

---

lib/MIP/Main/Analyse.pm
lib/MIP/Sample_info.pm
t/write_sample_info_to_file.t

feat(refactor): Added sub for writing of sample_info file to disk

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Main/Analyse.pm
lib/MIP/Update/Parameters.pm
t/set_vcfparser_outfile_counter.t

- Changed name of sub to set_vcfparser_outfile_counter
- Moved sub
- See above

feat(refactor): update_vcfparser_outfile_counter

---

definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm

Couldn't find this parameter in use anywhere

feat(cleanup): rm unused genomic_set :wastebasket:

---

lib/MIP/Analysis.pm
lib/MIP/Main/Analyse.pm
t/check_analysis_type_compatibility.t
t/check_analysis_type_to_pipeline.t

- checks that analysis type is compatible with pipeline

feat(analyse_check): check compatible pipeline

---

definitions/rd_dna_panel_parameters.yaml
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_gatk_baserecalibration_panel.t

feat(gatk_bsqr): panel recipe

---

lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm

feat(sambamba_depth):added to panel pipe

---

lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/data/643594-miptest/643594-panel_pedigree.yaml

feat(picard_metrics): added to panel pipe

---

lib/MIP/Check/Pipeline.pm
lib/MIP/Check/Reference.pm
lib/MIP/File_info.pm
t/check_parameter_metafiles.t

feat(refactor): check_parameter_metafiles

---

definitions/rd_dna_panel_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Program/Gatk.pm
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Analysis/Gatk_genotypegvcfs.pm
lib/MIP/Recipes/Analysis/Gatk_haplotypecaller.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_gatk_haplotypecaller_panel.t
t/gatk_genotypegvcfs.t
t/gatk_haplotypecaller.t

- adds haplotypecaller to panel pipe
- part of #1424 

feat(haplotypecaller): panel recipe

---

lib/MIP/Recipes/Analysis/Gatk_gathervcfs.pm
lib/MIP/Recipes/Analysis/Gatk_genotypegvcfs.pm
lib/MIP/Recipes/Analysis/Gatk_variantrecalibration.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm

- adds the wes flavour of gatk_genotypegvcfs, gatk_gathervcfs and gatk_variantrecalibration to panel pipe

feat(gent_and_vrecal): added to panel pipe

---

definitions/rd_dna_panel_initiation_map.yaml
definitions/rd_dna_panel_parameters.yaml
lib/MIP/Recipes/Analysis/Vt.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_vt_panel.t

- adds a vt recipe for the panel pipe

feat(vt): panel recipe

---

definitions/rd_dna_panel_parameters.yaml
lib/MIP/Recipes/Analysis/Frequency_annotation.pm
lib/MIP/Recipes/Analysis/Frequency_filter.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_frequency_annotation_panel.t
t/analysis_frequency_filter_panel.t

- adds frequency annotation and filtration to panel pipe

feat(freq_anno_filter): panel recipes

---

lib/MIP/Check/Parameter.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Vep.pm
t/check_vep_custom_annotation.t

feat(refactor): check_vep_custom_annotation

---

definitions/rd_dna_panel_parameters.yaml
lib/MIP/Language/Perl.pm
lib/MIP/Recipes/Analysis/Cadd.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_cadd_panel.t
t/mip_analyse_rd_dna_panel.test
t/perl_nae_oneliners.t

- adds cadd recipe to panel pipe

feat(cadd_ar): panel recipe

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Parameter.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Vep.pm
t/check_vep_plugin.t
t/parse_vep_plugin.t

- Moved sub
- Added parse sub
- Added test
- See above

feat(vep_plugins): Refactored

---

lib/MIP/Language/Perl.pm
lib/MIP/Recipes/Analysis/Vt.pm

- moves vt perl oneliner to oneliner sub

feat(vt_oneliner): refactor

---

definitions/rd_dna_panel_parameters.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Contigs.pm
lib/MIP/List.pm
lib/MIP/Program/Vep.pm
lib/MIP/Recipes/Analysis/Vep.pm
lib/MIP/Recipes/Pipeline/Analyse_dragen_rd_dna.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_vcf_rerun.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_vep.t
t/analysis_vep_rna.t
t/analysis_vep_wgs.t
t/get_splitted_lists.t
t/variant_effect_predictor.t

- modifies rna version of vep recipe to use different padding for mt
- use vep rna recipe in panel pipe
- part of #1424 

feat(vep): run vep in panel pipe

---

definitions/rd_dna_panel_parameters.yaml
lib/MIP/Check/Hash.pm
lib/MIP/Program/Bcftools.pm
lib/MIP/Recipes/Analysis/Mip_vcfparser.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_mip_vcfparser_panel.t
t/check_element_exist_hash_of_array.t

- adds vcfparser to panel pipe
- part of #1424 

feat(vcfparser_ar): panel recipe

---

cpanfile
lib/MIP/Io/Read.pm
lib/MIP/Io/Write.pm
lib/MIP/Test/Writefile.pm
lib/MIP/Toml.pm
t/write_toml.t
t/write_toml_config.t

- Added write function to controller
- Use new write function
- Added tests
- See above 

feat(Toml): Added Toml::Tiny

---

lib/MIP/Analysis.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Set/Parameter.pm
t/broadcast_parameters.t
t/set_parameter_to_broadcast.t

feat(refactor): set_parameter_to_broadcast

---

definitions/dragen_rd_dna_parameters.yaml
definitions/rd_dna_panel_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm
lib/MIP/Recipes/Analysis/Endvariantannotationblock.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
t/analysis_endvariantannotationblock_panel.t

- Adds endvariantannotation to panel pipe
- Removes cli option to output non compressed snv vcf from all pipes

Pan endvariantannotation

---

templates/mip_download_rd_dna_config_-1.0-.yaml

- Adds download of new vcfanno config

feat(download): New vcfanno config

---

lib/MIP/Analysis.pm
lib/MIP/Check/Pipeline.pm
lib/MIP/Update/Recipes.pm
t/update_program_mode_for_analysis_type.t
t/update_recipe_mode_for_wes.t

feat(refactor): update_program_mode_for_analysis_type

---

lib/MIP/Contigs.pm
lib/MIP/Delete/List.pm
lib/MIP/Recipes/Analysis/Cnvnator.pm
lib/MIP/Recipes/Analysis/Gatk_variantrecalibration.pm
lib/MIP/Update/Contigs.pm
t/delete_contig_elements.t

feat(refactor): delete_contig_elements

---

lib/MIP/Recipes/Analysis/Plink.pm
t/analysis_plink.t

- used to warn `Use of uninitialized value in string`

feat(plink): check for defined foun_other

---

lib/MIP/Active_parameter.pm
lib/MIP/Get/File.pm
lib/MIP/Parse/Parameter.pm
t/get_matching_values_key.t

feat(refactor): Sub get_matching_values_key

---

lib/MIP/Analysis.pm
t/parse_prioritize_variant_callers.t

- Skips the check if the parameter isn't part of the pipeline 

feat(prioritize_variant_callers): panel adaptation

---

definitions/download_parameters.yaml
lib/MIP/Cli/Mip/Download.pm
lib/MIP/Parse/Singularity.pm
lib/MIP/Recipes/Pipeline/Download_rd_dna.pm
lib/MIP/Recipes/Pipeline/Download_rd_rna.pm
t/data/references/grch37_gatk_merged_reference_samples.txt
t/reduce_dir_paths.t
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml

- removed environment name default as it took precedence over config value
- Modified download to bind reference dir to singularity containers

feat(download): small fixes

---

lib/MIP/File/Path.pm
lib/MIP/Get/File.pm
lib/MIP/Parse/Parameter.pm
t/get_file_names.t

feat(refactor): get_files

---

lib/MIP/Check/Parameter.pm
lib/MIP/Parse/Parameter.pm
lib/MIP/Validate/Case.pm
t/check_infiles.t

feat(refactor): check_infiles

---

CHANGELOG.md
containers/smncopynumbercaller/Dockerfile

feat(SMNCopyNumberCaller): Update to version 1.0

---

CHANGELOG.md
t/data/test_data/download_active_parameters.yaml
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

feat(loqusDB): Adds new loqusDB exports for snv/indels and SVs

---

.gitignore

feat(.gitignore): adds more to .gitignore

---

lib/MIP/File_info.pm
lib/MIP/Parse/File.pm
lib/MIP/Recipes/Analysis/Gzip_fastq.pm
lib/MIP/Set/File.pm
t/analysis_gzip_fastq.t
t/get_is_sample_files_compressed.t
t/get_sample_file_attribute.t
t/parse_fastq_infiles.t
t/parse_file_compression_features.t
t/parse_files_compression_status.t
t/set_is_sample_files_compressed.t
t/set_sample_file_attribute.t

- Refactor how to get and set compression features

feat(refactor): compression features

---

CHANGELOG.md
definitions/rd_dna_panel_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Qcc_regexp.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Analysis/Trim_galore.pm
lib/MIP/Recipes/Install/Mip_scripts.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/data/references/qc_eval_metric_-v1.1-.yaml
t/data/references/qc_regexp_-v1.25-.yaml
t/define_evaluate_metric.t
t/evaluate_analysis.t
t/mip_core.t
t/mip_qccollect.test
templates/mip_install_rd_dna_config_-1.0-.yaml
templates/mip_install_rd_rna_config_-1.0-.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml
templates/mip_rd_rna_config.yaml
templates/qc_eval_metric_-v1.1-.yaml
templates/qc_regexp_-v1.25-.yaml

- Adds Qcinspect to the rna pipeline
- Evaluates
- percentage_reads_with_adapter
- percentage_reads_after_trimming
- percentage_bp_after_trimming
- percentage_uniquely_mapped_reads
- fraction_duplicates
- Addresses #1371

feat(qccollect_rna): Collect and evaluate rna data

---

lib/MIP/Fastq.pm
lib/MIP/Sample_info.pm
t/define_mip_fastq_file_features.t
t/set_infile_info.t

- Refactoring of _file_name_formats

Feature/ file name formats

---

t/mip_analyse_dragen_rd_dna.test
t/mip_analyse_rd_dna.test
t/mip_analyse_rd_dna_vcf_rerun.test
t/mip_analyse_rd_rna.test
t/mip_download_rd_dna.test
t/mip_download_rd_rna.test
t/mip_qccollect.test
t/mip_vcfparser.test
t/mip_vercollect.test

feat(.test): Use child_process in all test scripts

---

lib/MIP/Analysis.pm
t/update_prioritize_flag.t

when conesensus_analysis_type is "wgs"
- Updated test

Feature/svdb prioritization: Added proper return of prioritization order 

---

lib/MIP/Program/Gatk.pm
t/gatk_indexfeaturefile.t

fix(gatk_indexfeaturefile): Changed flag from "input" to "feature-file"

---

lib/MIP/Check/Reference.pm
t/data/references/grch37_frequency_vcfanno_filter_config_-v1.0-.toml
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml

- Adds a flag to the toml config, which can be set to skip split and normalize 

feat(vcfanno_no_vt): new flag in toml

---

CHANGELOG.md
templates/mip_install_config.yaml
templates/mip_rd_rna_config.yaml

feat(arriba): program update

---

CHANGELOG.md
templates/mip_install_config.yaml

- updates multiqc to version 1.9

feature(multiqc): program update

---

CHANGELOG.md
t/check_vep_api_cache_versions.t
templates/mip_dragen_rd_dna_config.yaml
templates/mip_install_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml
templates/mip_rd_rna_config.yaml

- updates vep to version 100, 
- closes #1524 

feat(vep): program update

---

lib/MIP/Sample_info.pm
t/set_parameter_in_sample_info.t

feat(refactor): set_parameter_in_sample_info

---

lib/MIP/Analysis.pm
lib/MIP/Check/File.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/check_ids_in_dna_vcf.t

feat(refactor): check_ids_in_dna_vcf

---

lib/MIP/Active_parameter.pm
lib/MIP/Check/Parameter.pm
lib/MIP/Set/Parameter.pm
t/set_recipe_mode.t

feat(refactor): set_recipe_mode

---

lib/MIP/Analysis.pm
lib/MIP/Check/Parameter.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/update_recipe_mode_for_fastq_compatibility.t

feat(refactor): check_recipe_fastq_compatibility

---

lib/MIP/Analysis.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
lib/MIP/Set/Analysis.pm
t/set_ase_chain_recipes.t

feat(refactor): set_ase_chain_recipes

---

lib/MIP/Main/Analyse.pm
lib/MIP/Main/Download.pm
lib/MIP/Main/Install.pm

feat(refactor): Removed lexical copy active_parameters in MAIN

---

.coveralls.yml
.github/workflows/testing.yml
cpanfile
lib/MIP/Program/Tar.pm
t/analysis_bcftools_merge.t
t/star_fusion_gtf_file_to_feature_seqs.t
t/tar.t

- A replacement for travis CI
- Runs a workflow for a complete MIP install with all tests and coveralls report

feat(github_actions): Added test of perl install and units tests

---

lib/MIP/Environment/Container.pm
lib/MIP/Recipes/Install/Post_installation.pm
lib/MIP/Recipes/Pipeline/Install.pm
lib/MIP/Set/Parameter.pm
t/set_programs_for_installation.t

fix(installation): fixes some errors

---

.github/workflows/coverage.yml
.github/workflows/testing.yml

feat(github_actions): Added test suite without coverage calculation

---

lib/MIP/Recipes/Analysis/Expansionhunter.pm

- runs stranger with the variant catalog used with expansionhunter

feat(stranger): adds variant catalog

---

lib/MIP/Workloadmanager/Slurm.pm
t/slurm_build_sbatch_header.t
templates/code/module.pm

feat(refactor): slurm_build_sbatch_header

---

definitions/rd_dna_parameters.yaml
lib/MIP/Program/Bcftools.pm
lib/MIP/Recipes/Download/Gnomad.pm
t/bcftools_query.t

- Builds file allele frequency file for bcftools roh from gnomad data

feat(rhocall): Build frq file

---

lib/MIP/Program/Gnu/Coreutils.pm
t/gnu_rm.t

feat(gnu_rm): Use short flag for "--force" as well

---

templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml
templates/mip_rd_rna_config.yaml

fix(mip_config): update qc_collect and regexp

---

templates/mip_download_rd_dna_config_-1.0-.yaml

feat(mip_download): new vcfanno_config

---

templates/mip_install_config.yaml

- adds trim_galore the installation again

fix(trim_galore): fixes missing installation

---

lib/MIP/File/Decompression.pm
lib/MIP/Recipes/Download/Get_reference.pm

feat(download): Added file path to gzip decompression in download

---

lib/MIP/Language/Shell.pm
lib/MIP/Program/Gnu/Bash.pm
t/enable_trap.t
t/gnu_trap.t

- Refactors enable_trap and gnu_trap

feat(refactor): Enable trap

---

definitions/install_parameters.yaml
lib/MIP/Cli/Mip/Install.pm
templates/mip_install_config.yaml
templates/program_test_cmds.yaml

Install deepvariant

---

definitions/rd_dna_parameters.yaml
definitions/rd_rna_parameters.yaml
t/check_vep_custom_annotation.t
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

feat(update_refs):

---

containers/trim_galore/Dockerfile
templates/mip_install_config.yaml

- Moves trim_galore to docker 

feat(trim_galore): Dockerfile

---

templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml

- Download decoy variant of fai file

feat(download): decoy index

---

t/create_housekeeping_function.t

feat(refactor): create_housekeeping_function

---

lib/MIP/Recipes/Analysis/Bwa_mem.pm

feat(bwa:mem2): Split pipe before samtools sort

---

lib/MIP/Recipes/Download/Human_reference.pm
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml

- build fai file during download

feat(download): build_fai

---

definitions/rd_dna_parameters.yaml
lib/MIP/Recipes/Analysis/Smncopynumbercaller.pm
lib/MIP/Recipes/Analysis/Star_caller.pm
t/analysis_star_caller.t

feat(star_caller): move to case

---

lib/MIP/Main/Install.pm
lib/MIP/Pipeline.pm

- Removed some surplus code from Main::Install

feat(install): cleanup of main::install

---

lib/MIP/Recipes/Analysis/Gatk_variantevalexome.pm

feat(memory): Increase memory for gatk_indexfeaturefile

---

lib/MIP/Recipes/Analysis/Variant_annotation.pm

feat(vcfanno): removed log from submit_script

---

definitions/rd_rna_parameters.yaml
lib/MIP/Recipes/Analysis/Star_fusion.pm
lib/MIP/Recipes/Build/Rd_rna.pm
lib/MIP/Recipes/Download/Ctat_resource_lib.pm

feat(star_fusion): turn off building on ref

---

definitions/dragen_rd_dna_parameters.yaml
definitions/rd_dna_panel_parameters.yaml
definitions/rd_dna_parameters.yaml
definitions/rd_dna_vcf_rerun_parameters.yaml
lib/MIP/Program/Bcftools.pm
lib/MIP/Recipes/Analysis/Cadd.pm
lib/MIP/Recipes/Analysis/Frequency_filter.pm

- Fixes cadd whne MT lacks indels by adding another contig
- Limit the number of cores in use for cadd 

feat(cadd): fix for MT

---

templates/code/command_module.pm
templates/code/recipe_analysis_sample.pm
templates/code/recipe_download.pm
templates/code/recipe_install_shell.pm

feat(template): remove strict

---

lib/MIP/Program/Samtools.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm
t/samtools_sort.t

Samtools sort mem per thread

---

lib/MIP/Program/Slurm.pm
lib/MIP/Script/Setup_script.pm
t/slurm_build_sbatch_header.t
templates/code/recipe_analysis_case.pm
templates/code/recipe_analysis_sample.pm
templates/code/recipe_download.pm

- Removed log from setup_script args in templates
- See above

feat(qos): Removed slurm_quality_of_service from setup_script args

---

lib/MIP/Recipes/Download/Gnomad.pm
templates/mip_download_rd_dna_config_-1.0-.yaml

- downloads gnomad version 3 and calculates af_popmax

feat(gnomad): download r3.0

---

lib/MIP/Language/Perl.pm
lib/MIP/Recipes/Download/Get_reference.pm
lib/MIP/Validate/File.pm
t/check_file_md5sum.t
t/gnu_md5sum.t
t/gnu_rm.t

feat(refactor): Use perl module and move sub to Validate dir

---

containers/cnvnator/Dockerfile

feat(cnvnator): update to dockerfile

---

lib/MIP/Script/Setup_script.pm
t/data/test_data/download_active_parameters.yaml
t/download_1000g_indels.t
t/setup_script.t

- Added email_type to fixture
- See above

feat(refactor): Unpack email type when required and not before

---

lib/MIP/Program/Gnu/Coreutils.pm
t/gnu_echo.t
t/gnu_set.t
t/gnu_sleep.t
t/gnu_ulimit.t
t/gnu_unset.t

feat(refactor): Some gnu subs

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Smncopynumbercaller.pm

Smncopy sample 2

---

lib/MIP/Program/Htslib.pm
t/htslib_bgzip.t

- Multi-threading option for bgzip

Add multithreading option to bgzip

---

lib/MIP/Language/Perl.pm
lib/MIP/Recipes/Analysis/Mip_vcfparser.pm
lib/MIP/Sample_info.pm
t/set_gene_panel.t

feat(get_gene_panel): refactoring

---

CHANGELOG.md
lib/MIP/Constants.pm
templates/grch38_mip_rd_dna_config.yaml
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_dragen_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml
templates/mip_rd_dna_panel_config.yaml
templates/mip_rd_dna_vcf_rerun_config.yaml

- Add to mip download
- See above

feat(reference): Update clinvar to latest in archive

---

lib/MIP/Script/Setup_script.pm
t/create_script_temp_dir.t

feat(refactor): Created sub for creating temp dir in script

---

lib/MIP/Language/Shell.pm
lib/MIP/Script/Setup_script.pm
t/log_host_name.t
t/set_script_shell_attributes.t

feat(refactor): Shell attribbutes in setup_script

---

lib/MIP/Main/Install.pm
lib/MIP/Mip_install.pm
t/check_active_installation_parameters.t

feat(refactor): check_active_installation_parameters

---

t/analysis_analysisrunstatus.t

- Bumps test coverage back to 100%

feat(test): increase coverage

---

lib/MIP/Install.pm
lib/MIP/Recipes/Install/Mip_scripts.pm
t/check_mip_executable.t

- Refactor check_mip_executable

feat(refactor): check_mip_executable

---

t/install_container.t

feat(refactor): Remove test dir created by test script

---

lib/MIP/Processmanagement/Processes.pm
lib/MIP/Processmanagement/Slurm_processes.pm
lib/MIP/Recipes/Analysis/Sacct.pm
lib/MIP/Recipes/Download/Runstatus.pm
lib/MIP/Script/Setup_script.pm
t/analysis_sacct.t
t/create_script_error_trap.t
t/create_script_temp_dir.t
t/get_all_job_ids.t
t/processes_limit_job_id_string.t
t/slurm_sbatch.t
t/slurm_submit_chain_job_ids_dependency_add_to_path.t
t/slurm_submit_job_case_id_dependency_add_to_sample.t
t/slurm_submit_job_no_dependency_add_to_sample.t
t/slurm_submit_job_no_dependency_add_to_samples.t
t/slurm_submit_job_no_dependency_dead_end.t
t/slurm_submit_job_sample_id_dependency_add_to_case.t
t/slurm_submit_job_sample_id_dependency_add_to_sample.t
t/slurm_submit_job_sample_id_dependency_case_dead_end.t
t/slurm_submit_job_sample_id_dependency_dead_end.t
t/slurm_submit_job_sample_id_dependency_step_in_parallel.t
t/slurm_submit_job_sample_id_dependency_step_in_parallel_to_case.t

- Added all job_ids to "ALL" keys
- Remove "PAN" key usage
- Relax constraint on number of elements in "ALL" keys array to 1000

feat(job_ids): Added all job_ids to "ALL" keys

---

definitions/analyse_parameters.yaml
lib/MIP/Cli/Mip/Analyse.pm
mip_install_perl.sh
t/mip_analyse_dragen_rd_dna.test
t/mip_analyse_rd_dna.test
t/mip_analyse_rd_dna_panel.test
t/mip_analyse_rd_dna_vcf_rerun.test
t/mip_analyse_rd_rna.test

remove test mode for analysis

---

definitions/rd_rna_parameters.yaml
lib/MIP/Program/Star.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
t/analysis_star_aln.t
t/analysis_star_aln_mixed.t

feat(star): updates run parameter

---

Dockerfile
templates/mip_install_config.yaml

feat(Docker): Removed entrypoint and use PERL5LIB instead

---

README.md
documentation/Code/Best_practise.md
documentation/Code/Install/Adding_a_program.md
documentation/README.md
documentation/Setup.md

feat(doc): Updates installation documentation

---

lib/MIP/File/Format/Pli.pm
lib/MIP/Main/Vcfparser.pm
t/load_pli_file.t

feat(refactor): load_pli_file

---

definitions/rd_dna_parameters.yaml
lib/MIP/Recipes/Analysis/Bwa_mem.pm

feat(bwakit): start via docker

---

lib/MIP/File_info.pm
lib/MIP/Recipes/Analysis/Picardtools_mergesamfiles.pm
lib/MIP/Recipes/Analysis/Samtools_merge.pm
lib/MIP/Set/File.pm
t/get_merged_infile_prefix.t
t/set_merged_infile_prefix.t

feat(refactor): set_merged_infile_prefix

---

lib/MIP/File_info.pm
lib/MIP/Get/File.pm
lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
lib/MIP/Recipes/Analysis/Markduplicates.pm
t/get_merged_infile_prefix.t

- Moved sub
- Only modified import for recipies - the rest is perltidy

feat(refactor): get_merged_infile_prefix

---

lib/MIP/Active_parameter.pm
lib/MIP/Config.pm
lib/MIP/Update/Parameters.pm
t/update_dynamic_config_parameters.t

feat(refactor): Moved sub update_dynamic_config_parameters

---

lib/MIP/Analysis.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
lib/MIP/Set/Analysis.pm
t/set_recipe_gatk_variantrecalibration.t

feat(refactor): Move sub set_recipe_gatk_variantrecalibration

---

lib/MIP/File_info.pm
lib/MIP/Parse/Gender.pm
t/get_sampling_fastq_files.t

feat(refactor): Moved sub get_sampling_fastq_files

---

lib/MIP/Parse/Gender.pm
lib/MIP/Recipes/Analysis/Estimate_gender.pm
t/get_number_of_male_reads.t
t/parse_fastq_for_gender.t

feat(refactor): Move sub get_number_of_male_reads

---

lib/MIP/Parse/Gender.pm
lib/MIP/Recipes/Analysis/Estimate_gender.pm
t/update_gender_info.t

feat(refactor): Move sub update_gender_info

---

CHANGELOG.md
containers/stranger/Dockerfile
templates/mip_install_config.yaml

feat(stranger): updating 0.7 -> 0.7.1

---

templates/code/recipe_analysis_case.pm
templates/code/recipe_analysis_case.t
templates/code/recipe_analysis_sample.pm
templates/code/recipe_analysis_sample.t

feat(templates): update recipe tempalates

---

definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Recipes/Analysis/Svdb_merge_fusion.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_svdb_merge_fusion.t

- Merge sample fusions into a case fusion vcf

feat(merge_fusion): merge sample fusion to case

---

CHANGELOG.md
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(picard): Update picard to 2.25.0

---

definitions/rd_rna_parameters.yaml
lib/MIP/File_info.pm
lib/MIP/Recipes/Analysis/Arriba.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Analysis/Star_fusion.pm
t/analysis_star_fusion.t
t/get_sample_fastq_file_lanes.t

- Renames star fusion outfile so that it contains the sample id

feat(star_fusion): rename outfile

---

lib/MIP/Language/Perl.pm
lib/MIP/Recipes/Analysis/Bwa_mem.pm

feat(refactor): Moved oneliner to perl module

---

CHANGELOG.md
containers/tiddit/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(tiddit): Update TIDDIT

---

CHANGELOG.md
containers/sambamba/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(sambamba): Update sambamba

---

CHANGELOG.md
containers/cyrius/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(cyrius): Update

---

containers/bwa-mem2/Dockerfile
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- bwa-mem2 was updated with a hotfix that adressess a memory error. I haven't tested yet if it solves our error

feat(bwa-mem2): update

---

CHANGELOG.md
containers/sambamba/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

rollback sambamba update

---

CHANGELOG.md
documentation/Setup.md
lib/MIP/Program/Gatk.pm
t/data/test_data/install_active_parameters.yaml
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

update gatk version

---

CHANGELOG.md
containers/star/Dockerfile
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- updates star to version 2.7.8a

feat(star): program update

---

lib/MIP/Recipes/Analysis/Bcftools_merge.pm
lib/MIP/Recipes/Analysis/BootstrapAnn.pm
lib/MIP/Recipes/Analysis/Vep.pm

- removed some rna files from deliverables

feat(rna_deliverables): removed some files

---

containers/megafusion/Dockerfile
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(megafusion): program update

---

CHANGELOG.md
templates/mip_download_rd_rna_config_-1.0-.yaml

update gencode references

---

CHANGELOG.md
templates/grch38_mip_rd_rna_config.yaml
templates/mip_download_rd_rna_config_-1.0-.yaml
templates/mip_rd_rna_config.yaml

- updates gencode annotations to version 37

feat(gencode annotations): reference update

---

CHANGELOG.md
containers/bedtools/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(bedtools): program update

---

CHANGELOG.md
containers/delly/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(delly): program update

---

t/analysis_bcftools_norm_panel.t

- Fixing code coverage for bcftools_norm panel recipe

feat(bcftools_norm): fixing coverage

---

CHANGELOG.md
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

feat(glnexus): program update

---

CHANGELOG.md
containers/htslib/Dockerfile
documentation/Setup.md
lib/MIP/Constants.pm
lib/MIP/Program/Bcftools.pm
t/bcftools_norm.t
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- updates htslib
there are some new options to bcftools norm that could be useful

feat(htslib): program update

---

CHANGELOG.md
containers/upd/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- updates upd to version 0.1.1
This version of upd changes HOMODISOMY to ISODISOMY in the output file. Will this be a problem for chromograph @mikaell? 

feat(upd): program update

---

CHANGELOG.md
containers/chromograph/Dockerfile
documentation/Setup.md
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- updates chromograph to version 1.1

feat(chromograph): program update

---

templates/grch38_mip_rd_rna_config.yaml
templates/mip_rd_rna_config.yaml

- updates the vep cache path in the template config

feat(rna_config_template): update vep cache path

---

containers/blobfish/Dockerfile

- Fixes the docker image for blobfish (DESeq2)

feat(blobfish): updates dockerfile

---

lib/MIP/Store.pm

- Adds some qc metrics to the case qc metrics deliverables file

feat(rna_qc): adds some qc metrics to deliverable

---

CHANGELOG.md

fix DeepVariant version typo in changelog

---

lib/MIP/Recipes/Analysis/Bcftools_norm.pm
t/analysis_bcftools_norm.t
t/analysis_bcftools_norm_panel.t
t/check_vep_api_cache_versions.t

- The bcftools_core recipe wasn't compatible with an already opened filehandle. The bcftools_norm recipe now calls the bcftools program directly.

feat(bcftools_norm): refactor

---

CHANGELOG.md
containers/stranger/Dockerfile
documentation/Setup.md
t/data/test_data/install_active_parameters.yaml
t/data/test_data/miptest_install_config.yaml
templates/mip_install_config.yaml

- Stranger update from 0.7.1 -> 0.8.0

Update stranger version

---

CHANGELOG.md
definitions/rd_rna_parameters.yaml
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Glnexus.pm
t/analysis_glnexus.t
templates/mip_install_config.yaml

- Changing which file that is normalised in the glnexus recipe for a single sample case. [#1205](https://github.com/Clinical-Genomics/cg/pull/1205)

updating glnexus recipe

---

templates/mip_download_rd_dna_config_-1.0-.yaml

- there were misstakes in the url:s

fixing download paths

---

CHANGELOG.md
containers/hmtnote/Dockerfile
definitions/install_parameters.yaml
definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Install.pm
lib/MIP/Program/HmtNote.pm
lib/MIP/Recipes/Analysis/Mt_annotation.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
t/analysis_mt_annotation.t
t/hmtnote_annotate.t
templates/mip_install_config.yaml

installing hmtnote

---

definitions/analyse_parameters.yaml
definitions/rd_dna_panel_parameters.yaml
definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm

- moves `set_recipe...`to analyse level

set rna resources via cli

---

containers/glnexus/Dockerfile
templates/mip_install_config.yaml

Update glnexus uri and dockerfile

---

containers/glnexus/Dockerfile

- Updates glnexus_cli exec permission within the container

Update glnexus exec permission

---

definitions/rd_dna_initiation_map.yaml
lib/MIP/Recipes/Analysis/Mt_annotation.pm
lib/MIP/Recipes/Analysis/Variant_annotation.pm
t/mip_analyse_rd_dna.test

- The loqus db headers weren't added to the correct file

fixing annotation recipe

---

lib/MIP/Recipes/Analysis/Endvariantannotationblock.pm

- Changes gatk gathervcfs to bcftools concat in the endvariantannotationblock recipe. The header of the MT vcf is different to the others since we run hmtnote on that file. That causes gatk gathervcfs to fail, complaining that not all annotations in the INFO field is part of the header. Bcftools seems to be able to handle it though  

change to bcftools concat

---

CHANGELOG.md
containers/bootstrapann/Dockerfile
definitions/rd_rna_initiation_map.yaml
definitions/rd_rna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_rna.pm
lib/MIP/Constants.pm
lib/MIP/Environment/Container.pm
lib/MIP/Program/Star.pm
lib/MIP/Program/Star_fusion.pm
lib/MIP/Recipes/Analysis/Glnexus.pm
lib/MIP/Recipes/Analysis/Star_aln.pm
lib/MIP/Recipes/Analysis/Star_fusion.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
t/analysis_star_fusion_aln.t
t/data/test_data/miptest_install_config.yaml
t/star_aln.t
t/star_fusion.t
templates/mip_install_config.yaml

- Hotfix to add tempdirecory for Star-Fusion in an attempt to avoid timeout, also includes a RNA resource bump

MIP 10.2.4

---

.pre-commit-config.yaml
CHANGELOG.md
definitions/rd_dna_panel_parameters.yaml
lib/MIP/Cli/Mip/Analyse.pm
lib/MIP/Cli/Mip/Download.pm
lib/MIP/Constants.pm
lib/MIP/Program/Slurm.pm
templates/mip_install_config.yaml

adds qos flag express

---

CHANGELOG.md
lib/MIP/Pedigree.pm
lib/MIP/Recipes/Analysis/Chromograph.pm
lib/MIP/Recipes/Analysis/Upd.pm
t/is_sample_proband_in_trio.t

runs upd and chromograph on unaffected children

---

CHANGELOG.md
containers/expansionhunter/Dockerfile
definitions/rd_dna_parameters.yaml
lib/MIP/Program/Expansionhunter.pm
lib/MIP/Recipes/Analysis/Expansionhunter.pm
t/expansionhunter.t
t/mip_analyse_rd_dna.test
templates/mip_install_config.yaml

updates expansionhunter and saves output

---

CHANGELOG.md
containers/chromograph/Dockerfile
documentation/Setup.md
lib/MIP/Constants.pm
templates/mip_install_config.yaml

- Updates chromograph to version 1.1.5

updates chromograph to version 1.1.5

---

CHANGELOG.md
lib/MIP/Active_parameter.pm
lib/MIP/Constants.pm
lib/MIP/Environment/Manager.pm
lib/MIP/Program/Conda.pm
lib/MIP/Script/Setup_script.pm
t/conda_activate.t
t/get_env_method_cmds.t
t/get_package_env_cmds.t
t/get_recipe_resources.t
t/mip_analyse_rd_dna.test
t/parse_recipe_prerequisites.t
templates/mip_install_config.yaml

initiate conda

---

CHANGELOG.md
containers/chromograph/Dockerfile
lib/MIP/Constants.pm
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_install_config.yaml

- Updates chromograph 
- added missing vcfanno config to the download config

updates chromograph

---

CHANGELOG.md
definitions/rd_dna_parameters.yaml
lib/MIP/Constants.pm
templates/mip_download_rd_dna_config_-1.0-.yaml
templates/mip_install_config.yaml

- Updates the variant catalog for expansionhunter

updates variant catalog for expansionhunter

---

CHANGELOG.md
definitions/rd_rna_parameters.yaml

- mem increase for picardtools mergesamfiles (RNA)

increase mem for picardtools mergesamfiles

---

CHANGELOG.md
lib/MIP/Constants.pm
lib/MIP/Recipes/Analysis/Mitodel.pm
templates/mip_install_config.yaml

- Fixes a bug in the mitochondrial deletion script, see issue https://github.com/Clinical-Genomics/MIP/issues/2016

release 11.1.2

---

CHANGELOG.md
containers/retroseq/Dockerfile
definitions/install_parameters.yaml
definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
documentation/Setup.md
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Cli/Mip/Install.pm
lib/MIP/Constants.pm
lib/MIP/Program/Retroseq.pm
lib/MIP/Recipes/Analysis/Retroseq.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
t/analysis_retroseq.t
t/retroseq_call.t
t/retroseq_discover.t
templates/grch38_mip_rd_dna_config.yaml
templates/mip_install_config.yaml
templates/mip_rd_dna_config.yaml

- Adds the retroseq recipe together with tests. Retroseq operates on bam files from markduplicates and consists of a two step process, `discover` and `call`.

adding retroseq

---

definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Program/Svdb.pm
lib/MIP/Recipes/Analysis/Svdb_merge_me.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
t/analysis_me_merge_vcfs.t
t/svdb_merge.t

- merges sample vcfs with mobile elements to a case vcf, which is saved to deliverables

merge mobile element vcfs

---

definitions/rd_dna_initiation_map.yaml
definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Program/Bcftools.pm
lib/MIP/Recipes/Analysis/Me_annotate.pm
lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
t/analysis_me_annotate.t
t/bcftools_annotate.t
templates/grch38_mip_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml

- Annotates the called mobile elements with swegen frequencies using svdb. 
- Annotates the called mobile elements with exon overlap using bcftools annotate. 

Annotate me

---

definitions/rd_dna_parameters.yaml
lib/MIP/Cli/Mip/Analyse/Rd_dna.pm
lib/MIP/Recipes/Analysis/Me_annotate.pm
templates/grch38_mip_rd_dna_config.yaml
templates/mip_rd_dna_config.yaml

- After discussions with Daniel and Jesper we decided to remove the custom exon annotation and instead rely on VEP

removed me exon annotation

---

CHANGELOG.md
definitions/rd_dna_parameters.yaml
templates/mip_download_rd_dna_config_-1.0-.yaml

- Updates the expansionhunter catalog to include the FGF14 intronic expansion, https://github.com/Clinical-Genomics/reference-files/pull/57

updating expansionhunter database

---

CHANGELOG.md
lib/MIP/Constants.pm
templates/mip_install_config.yaml

- Patching of gens pre-processing container to solve an issue with incomplete bed files.

patching gens pre-processing script

---

CHANGELOG.md
templates/mip_download_rd_dna_config_-1.0-.yaml

uppdates clinvar references

---

CHANGELOG.md
templates/mip_download_rd_dna_config_-1.0-.yaml

- updates the clinvar and loqusdb

loqus and clinvar update
