Clinical-Genomics/MIP

t/contigs_set_contigs.t
No more special case when setting contigs for structural variants
=> fix for the set contig test, #429

.travis.yml, README.md, definitions/cpanfile, definitions/install_rare_disease_parameters.yaml, definitions/install_rna_parameters.yaml, documentation/README.md, lib/MIP/Cli/Mip/Install.pm, lib/MIP/Cli/Mip/Install/Rare_disease.pm, lib/MIP/Cli/Mip/Install/Rna.pm, lib/MIP/Main/Install.pm, lib/MIP/Recipes/Install/Conda.pm, lib/MIP/Recipes/Install/Svdb.pm, lib/MIP/Recipes/Install/Vcf2cytosure.pm, lib/MIP/Recipes/Install/Vep.pm, lib/MIP/Script/Utils.pm, t/mip_install.test
- Changed the installation so that all the environments can be installed in one go, fixes #449 
- Added trinity to RNA installation. It got it's own environment since it requires a threaded perl installation, fixes #435 
- SVDB has now been added to the main MIP environment. The dependency of Scikit-learn has been dropped in the most recent version of SVDB and it doesn't seem to disturb anything else. The installation script still installs an SVDB environment but it could possibly be removed later. There is also a conda version of SVDB that has been commented out of the config file. The conda version is a bit older and I don't know if it is fully compatible with the other programs in the main environment.
=> Overhauled the installation and added trinity to the RNA installation,

README.md
The travis badge on MIP's master branch reflected the build status for the develop branch
=> Change travis badge to reflect build status on master

.perlcriticrc_mip, documentation/Code/Best_practise.md, mip-check
Draft for a simple bash script that automates perltidy and perlcritic. As default it runs on the files that are new or have been modified. Perl critic severity has been set to level 2 as default. Increased the code line length to 90 and tried to change the number of lines in between open and close filehandles. 
Later we can include a check to see that the $VERSION line has been updated for modified files. Open for suggestions on how to change it or modify the behaviour of perlcritic and perltidy further (or skip modifications all together)
=> program for running mip code checks

lib/MIP/Recipes/Analysis/Gffcompare.pm
Since we only run gffcompare with one input file, the output file will
always be names [SOMETHING].annotated.gtf. 
Remove dead if block :fire:
=> fix(gffcompare): Removed dead code

lib/MIP/Qc_data.pm, qccollect.pl, t/add_to_qc_data.t
- How metrics without a data header are added to qc_data. Mainly a refactoring without any new functionality.
=> feat(refactor): Add data metrics without header to qc_data

definitions/download_rd_dna_parameters.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Recipes/Download/Delly_exclude.pm, lib/MIP/Recipes/Pipeline/Download_rd_dna.pm, t/data/test_data/download_active_parameters.yaml, t/download_delly_exclude.t, templates/mip_download_rd_dna_config_-1.0-.yaml
both grch37 and hg38. Fix #831.
- #831
- Manual download using mip download
- Mip downloads delly exclude files for grch37 and hg38
=> feat(delly_exclude): Added download of exclude file for delly calling

lib/MIP/Qc_data.pm, qccollect.pl, t/parse_qc_recipe_data.t
- Moves parsing of qc data recipe for table metrics to its own pm
=> feat(qccollect): Moved parse_qc_recipe_data to Qc_data

CHANGELOG.md, definitions/rd_dna_initiation_map.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, lib/MIP/Constants.pm, lib/MIP/Program/Variantcalling/Tiddit.pm, lib/MIP/Recipes/Analysis/Tiddit_coverage.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm, t/analysis_tiddit_coverage.t, t/tiddit_coverage.t, templates/mip_rd_dna_config.yaml
Added sample level recipe. Fix  #863
- Added "-w" option to tiddit_coverage API
- Added new MIP CLI tiddit coverage bin size and connected it to
tiddit, tiddit_coverage and vcf2cytosure_ar
- Added new sample level recipe: tiddit_coverge
- Placed it in the init map after BAM recal
- #863 
=> feat(tiddit_cov): Added generation of wig outfile from tiddit_coverage.

lib/MIP/Program/Mip.pm, lib/MIP/Recipes/Analysis/Mip_vcfparser.pm, t/mip_vcfparser.t
- The vcfparser log is generated at the place where MIP is executed which can lead to unexpected behaviour. With this pull request the log is created in the vcfparser_ar directory for each case. 
=> feat(vcfparser): set path for vcfparser.log

lib/MIP/Recipes/Analysis/Tiddit_coverage.pm
Removes the suffix from the outfile path given to tiddit. Tiddit will give the outfile a suffix depending on which outfile format that was chosen. 
=> fix(tiddit_coverage): outfile_path_prefix

definitions/download_rd_dna_parameters.yaml, definitions/download_rd_rna_parameters.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Check/File.pm, lib/MIP/Recipes/Analysis/Analysisrunstatus.pm, lib/MIP/Recipes/Download/Runstatus.pm, lib/MIP/Recipes/Pipeline/Download_rd_dna.pm, lib/MIP/Recipes/Pipeline/Download_rd_rna.pm, t/check_mip_process_files.t, t/download_runstatus.t
- Runstatus will check file existence
- Always execute after all potential downloads have completed
- Write to stderr if an expected file has not been found and also exit
with an error code of "1"
- Write to stdout for all files that are found
- Adds a sacct command in trap functions to write each STATUS of
download recipes to "log.status" file just like in analysis
- Added to both rd_dna and rd_rna pipelines
- Added tests
- The above
=> feat(download_check): Added runstatus recipe for download pipelines. Fix

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Mip_vcfparser.pm
not part of gene panel
- See above
=> fix(vcfparser): Fixed bug with outfile path when mitochondria contig is

definitions/rd_dna_parameters.yaml, templates/grch38_mip_rd_dna_config.yaml, templates/mip_rd_dna_config.yaml
- Removed sv_vep_feature "regulatory"
- Switched off delly_call and delly_reformat
- Removed delly from svdb prio string
- Set default string in parameters
=> feat(vep and delly): Modifed parameters

lib/MIP/Recipes/Analysis/Expansionhunter.pm, lib/MIP/Recipes/Analysis/Gatk_baserecalibration.pm
BAM index file and reading the file being copied.
- Create index file required for Expansionhunter in gatk baserecal
recipe instead of in expansionhunter recipe
- Sambamba depth error 
=> feat(sambamba_index): Detected a possible race condition between cp of

lib/MIP/Get/Parameter.pm
Since the RNA pipeline doesn't have the capture_kit key in it's pedigree the parameter $active_parameter_href->{exome_target_bed} is undef. This caused problem for the get_gatk_intervals sub in the baserecalibration recipe where it was required to be a hash. In this sub the parameter is only needed for wes. There is still a type check for wes samples on that parameter, where it is actually needed.     
=> fix(rna): no capture kit for rna

lib/MIP/Recipes/Install/Vep.pm
Turns out that I spelled LoFtool wrong, preventing the installation of that plugin. 
=> fix(install_vep): fix plugin name for LoFtool

containers/Singularity.chromograph-0.1, containers/Singularity.chromograph-0.2, definitions/rd_dna_initiation_map.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Recipes/Analysis/Chromograph.pm, lib/MIP/Recipes/Analysis/Tiddit_coverage.pm, lib/MIP/Recipes/Pipeline/Analyse_dragen_rd_dna.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna_vcf_rerun.pm, lib/MIP/Set/Analysis.pm, t/analysis_chromograph_proband.t, t/set_recipe_chromograph.t
- Moved rhocall_viz to its own chain and left recipe switch default to
0
- Turned off upd recipe switch and removed from inititatio map, but left recipes intact
- Split chromograph recipes into one recipe when processing only
tiddit_coverage data (not proband and in trio) and another recipe when
proband in trio and then processing both tiddit_coverage and UPD (within
recipe).
- Added chromograph recipe switch in pipeline engine for using correct
recipe depending on trio and proband status. All members will always
be processed by either one of the chromograph recipes.
- Modifed tiddit_coverage io in stream for correct inheritance
- Chromograph dependecies issues
=> feat(chromograph): Modifed chromograph dependencies and recipes

lib/MIP/Recipes/Analysis/Varg.pm
- Uses the .gz vcf files as varg input
=> Varg should use vcf.gz

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Endvariantannotationblock.pm
counter in recipe. Otherwise we will lose the select vcf when turning
off all sv modules
- See above
=> hotfix(vcfparser_counter): Use the snv/indel counter instead of sv

lib/MIP/Recipes/Analysis/Endvariantannotationblock.pm
recipe. Otherwise we will lose the select vcf
- See above
=> bug(vcfparser_count): Use the snv/indel counter instead of sv counter in

definitions/rd_rna_parameters.yaml, lib/MIP/Recipes/Analysis/Expansionhunter.pm
- fixes representation of multiallelic str calls
- resolves #1169 
=> bug(expansionhunter): switches vt svdb order

templates/mip_install_rd_dna_config_-1.0-.yaml
=> feat(rtg_docker): Use official rtg docker image uri in mip install

lib/MIP/Recipes/Analysis/Markduplicates.pm
recipe level key to avoid qccollect scanning the entire bam/cram file.
- Removed extra "." from infile id for markduplicate_alignemnt in qccollect
- See above
=> fix(qccollect_markdup): Moved record of alignment file to separate

lib/MIP/Parse/Gender.pm, t/update_gender_info.t
size
- See above
**Investigated values for the parameters BYTE_START_POS and BYTE_STOP_POS** 
BYTE_START_POS = 10,000 and 50,000
BYTE_STOP_POS = 1,000,000, 2,000,000 and 3,000,000
**Runtime**
Below is the runtime on 6 threads for the different start and stop positions.
Sample | 10,000_1,000,000 | 10,000_2,000,000 | 10,000_3,000,000
-- | -- | -- | --
SVE2623A1 | Real time:   4.551 sec; CPU: 7.036 sec | Real time:   4.925 sec; CPU: 10.615 sec | Real   time: 5.652 sec; CPU: 14.519 sec
ACC6346A4 | Real time: 3.794 sec; CPU: 4.310 sec | Real time: 4.146 sec; CPU: 6.123 sec | Real time: 4.835 sec; CPU: 8.306 sec
ACC4167A1 | Real time:   4.258 sec; CPU: 6.091 sec | Real time:   4.681 sec; CPU: 9.827 sec | Real   time: 4.543 sec; CPU: 14.222 sec
**Results**
Group (start_stop_gender) | Min | Max | …
=> feat(parse_for_gender): Updated constants for male threshold and chunk

lib/MIP/Cli/Mip/Analyse/Dragen_rd_dna.pm, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, lib/MIP/Cli/Mip/Analyse/Rd_dna_vcf_rerun.pm, lib/MIP/Cli/Mip/Analyse/Rd_rna.pm, lib/MIP/Get/Analysis.pm, lib/MIP/Parameter.pm, t/get_order_of_parameters.t
- Modified print_recipes args to directly use order_parameters instead of definition file
- Added test
- See above
=> feat(get_order_of_parameters): Added new sub to get order of parameters

.travis.yml, cpanfile, lib/MIP/Check/Modules.pm, lib/MIP/Check/Unix.pm, lib/MIP/Main/Analyse.pm, lib/MIP/Main/Vercollect.pm, lib/MIP/Recipes/Install/Mip_scripts.pm, lib/MIP/Set/Parameter.pm, mip, t/mip_analysis.test, t/mip_core.t
Last merge to develop introduced some bugs. 
- Reverts back to using YAML instead of YAML::XS since $YAML::XS::QuoteNumericStrings = 1 didn't seem to work properly. This could most likely be fixed with a clearer head...
- Adds a special case for Readonly::XS when checking for installed cpan modules.
- Updates the path to the cpanfile for those scripts that are using it. 
- Some other random fixes
=> fix(cpan stuff): fixes for cpan modules

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Gatk_splitncigarreads.pm
- Loop over bam contigs in gatk splitncigarreads
=> fix(splitncigarreads): loop over Y for F

lib/MIP/Recipes/Analysis/Markduplicates.pm
- Increases java memory to 6gb from 4
=> fix(markduplicates): increase java mem

lib/MIP/Recipes/Analysis/Rtg_vcfeval.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm
- adds gatk_combinevariantcallsets, gatk_variantevalall, rtg_vcfeval and variant_integrity to panel pipe
- part of #1424 
=> feat(panel_pipe): variantcall finish up

CHANGELOG.md, lib/MIP/Check/Reference.pm, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Chromograph.pm, lib/MIP/Recipes/Analysis/Gatk_combinevariantcallsets.pm, lib/MIP/Recipes/Analysis/Sambamba_depth.pm, lib/MIP/Sample_info.pm, t/check_if_processed_by_vt.t, t/check_references_for_vt.t
- Adds output files to store for
- gatk_combinevariants recipe
- sambamba depth recipe
- chromograph recipe
- Use MIPs bcftools singularity image for processing VT references
1. Automatic and continuous test suite
1. Run `cg workflow mip-dna run -p low  vitalmouse`
1. Run `cg workflow mip-dna run -p low  vitalmouse`
1. Installation, unit and integration test suite pass
1. gatk_combinevariants, sambamba depth and chromograph recipe outfiles should be in the deliverables file ✅ 
1. Reference are check for VT processing ✅ 
=> Add to deliverables file

lib/MIP/Check/Parameter.pm, lib/MIP/Parse/File.pm, lib/MIP/Validate/Case.pm, t/check_infile_contain_sample_id.t
- Refactored parse_fastq_infiles to make the sub more coherent
- Moved sub check_infile_contain_sample_id
- See above
=> feat(refactor): Sub check_infile_contain_sample_id

lib/MIP/Active_parameter.pm, lib/MIP/Check/Pipeline.pm, lib/MIP/Config.pm, lib/MIP/Contigs.pm, lib/MIP/Main/Analyse.pm, lib/MIP/Parse/Gender.pm, lib/MIP/Recipes/Analysis/Plink.pm, t/analysis_plink.t, t/delete_male_contig.t, t/parse_fastq_for_gender.t, t/set_gender_sample_ids.t, t/set_include_y.t, t/update_contigs_for_run.t, t/update_gender_info.t
- Removes the counters: 'found_female', 'found_male', 'found_other' from active_parameters and replaces it with the bolean 'include_y'
=> feat(include_y): found_male --> include_y

lib/MIP/Fastq.pm, lib/MIP/File_info.pm, lib/MIP/Parse/File.pm, lib/MIP/Sample_info.pm, t/add_sample_fastq_file_lanes.t, t/get_fastq_file_header_info.t, t/parse_sample_fastq_file_attributes.t, t/set_infile_info.t
- Added new sub add_sample_fastq_file_lanes and use it parse_sample_fastq_file_attributes
- Set file sample file info data in get_fastq_file_header_info
- Modify call to set_infile_info
- See above
=> feat(refactor): set_infile_info and get_fastq_file_header_info

lib/MIP/Recipes/Download/Vcfanno_config.pm
- Regex now accepts spaces arount the equal sign
- see above
=> feat(vcfanno_config): regex update

definitions/dragen_rd_dna_parameters.yaml, templates/mip_dragen_rd_dna_config.yaml
- sets picardtools_path for the dragen pipe. This wasn't set previously which caused a 'use of unintialized parameter' warning when thesting 
=> fix(dragen_analysis_test): sets picardtools_path

lib/MIP/Recipes/Analysis/Samtools_subsample_mt.pm, t/analysis_samtools_subsample_mt.t
- MIP crashing when using running a wgs analysis and excluding the MT contig
=> fix(exclude_contig_MT): In samtools_subsample_mt

CHANGELOG.md, lib/MIP/Constants.pm, templates/mip_install_rd_dna_config_-1.0-.yaml, templates/mip_install_rd_rna_config_-1.0-.yaml
- Updates multiqc to version 1.9. This fixes a known bug in multiqc which causes the program to crash with a ZeroDivisionError
=> fix(multiqc): updates multiqc

lib/MIP/Constants.pm, lib/MIP/Environment/Path.pm, lib/MIP/Parse/Singularity.pm, t/check_vcf_variant_line.t, t/reduce_dir_paths.t
- Import Test::Trap is now imported at the correct place in check_vcf_variant_line
- See above and mainly a move of the entire reduce_dir_paths sub
=> feat(refactor): reduce_dir_paths

lib/MIP/Analysis.pm, t/build_perl_program_check_command.t, t/set_ase_chain_recipes.t
- Changes check for dna vcf from a count check to a defined and exists check since the variable will be undefined if the file is missing
=> fix(ase_recipes): set correct ase recipes

lib/MIP/Program/Gnu/Coreutils.pm, t/gnu_cp.t
- Refactor gnu_cp
- Use short flags for recursiv and force to become more platform independent
=> feat(gnu_cp): Refactor and use some short flags instead of long

definitions/rd_dna_parameters.yaml, lib/MIP/Program/Picardtools.pm, lib/MIP/Recipes/Analysis/Rhocall.pm, t/picardtools_updatevcfsequencedictionary.t
- Updates the vcf sequence dictionary in the vcf prior to running rhocall viz
=> feat(rhocall_viz): updates sequence dictionary

containers/trim_galore/Dockerfile
- needed to resolve a java error in the trim galore container (at least for version 0.6.4)
=> fix(trim_galore): adds fontconfig to Dockerfile

lib/MIP/Cluster.pm, lib/MIP/Recipes/Analysis/Trim_galore.pm
- speeds up trim-galore by using the parallelisation option
The way the --cores option is calculated is somewhat convoluted:
https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#full-list-of-options-for-trim-galore
=> feat(trim-galore): parallelisation

definitions/rd_dna_panel_parameters.yaml, definitions/rd_dna_parameters.yaml
- Switch back to using bwa_mem as default since bwa_mem2 casued edge case errors on validation at least 2 validation cases
=> feat(bwa_mem): swithed back to using bwa_mem as default

lib/MIP/Main/Qccollect.pm
- relation_check will error if plink has not been processed, which can happen for wgs single samples
=> feat(qccollect): Added check for keys before calling sub

lib/MIP/Sample_info.pm
- The 'files' key in the sample_info hash accumulates the same store files between runs of he same sample. This PR introduces a check for that and deletes any old hash_ref with the same path key. 
=> feat(sample_info_files): remove duplicates

lib/MIP/Environment/Container.pm, lib/MIP/Environment/Executable.pm, lib/MIP/Language/Perl.pm, lib/MIP/Recipes/Analysis/Mip_vercollect.pm, t/get_binary_version_cmd.t, t/perl_nae_oneliners.t, t/write_binaries_versions.t
- Writes commands to get binary versions directly in recipe instead of going via mip_vercollect. This avoids the challenge of calling a container from a container.
- Fixed picard and vcfcytosure version commands
- Leaved mip_vercollect functionality intact for use in mip_install later
=> Vercollect recipe

lib/MIP/Recipes/Pipeline/Analyse_dragen_rd_dna.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna_panel.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna_vcf_rerun.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_rna.pm
- move the setting of container constants as they are needed early
=> feat(container_constants): move set sub

lib/MIP/Recipes/Analysis/Rtg_vcfeval.pm
- Feeds the correct infile path for rtg_vcfeval
=> Update infile path in rtg_vcfeval

definitions/rd_dna_parameters.yaml, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm, lib/MIP/Set/Analysis.pm, t/set_recipe_deepvariant.t
- Use deepvariant for duos and trios for now. 
I don't know if you were working on this already Ram but I was running some samples for the rna project and decided to turn off deeptrio for now. Let me know if you already have something else planned
=> feat(deeptrio): turned off as default

lib/MIP/Analysis.pm, lib/MIP/Recipes/Pipeline/Analyse_dragen_rd_dna.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna_vcf_rerun.pm, lib/MIP/Set/Analysis.pm, t/set_recipe_on_analysis_type.t
- Extend test
- Use get_cache sub instead of traversing parameter hash directly
- See above 
=> feat(refactor): Move sub set_recipe_on_analysis_type

definitions/rd_dna_parameters.yaml
- Set deepvariant to use CPUs and not GPUs by default
=> set default gpu number for deepvariant to 0

lib/MIP/Recipes/Analysis/Gatk_genotypegvcfs.pm
- Cleanup the genotypegvcf directory by removing the databases after use
=> feat(gatk): rm genotypegvcf DB at the end

CHANGELOG.md, containers/bwa-mem2/Dockerfile, definitions/rd_dna_panel_parameters.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm, t/data/test_data/miptest_install_config.yaml, templates/mip_install_config.yaml
- Updates bwa-mem2 to version 2.2. 
The issue with certain fastq files persists. 
E.g. when running fastq pair 5_171015_HKG2VCCXX-21-undetermined_ADM1274A1_XXXXXX_{1,2}.fastq.gz. Bwa-mem2 truncates the quality string of read `ST-E00269:46:HKG2VCCXX:5:2201:14113:4034`, causing samtools to fail. Mapping with the original bwa does not lead to this truncation. The read and quality string has the same length in the fastq file. It works if that read is removed from the fastq file. I'll see if I can formulate this in an issue on the mem2 repo
We are still using mem2 when doing the gender estimation so it might still be useful o update.
=> feat(bwa-mem2): 2.0 --> 2.2

definitions/rd_rna_parameters.yaml, lib/MIP/Recipes/Analysis/Salmon_quant.pm, t/analysis_salmon_quant.t
- renames generic salmon outfile name (quant.sf) to sample specific same
=> feat(salmon): rename outfile

definitions/rd_rna_parameters.yaml
Ran into a sample with a lot of reads causing memory failures and timeouts
- Increases memory and time for the arriba, star and star-fusion recipes
=> feat(rna_resources): increase star, star-fusion, arriba resources

definitions/rd_rna_parameters.yaml, lib/MIP/Recipes/Analysis/Arriba.pm, lib/MIP/Recipes/Analysis/Fusion_report.pm, templates/mip_download_rd_rna_config_-1.0-.yaml, templates/mip_install_config.yaml
- Use the gencode annotation covering the primary assembly instead of only the chromosomes
- Scaled down the memory used for samtools sort
- RNA resource bumps
=> feat(rna): resource bumps and fixes

lib/MIP/Recipes/Analysis/Bcftools_core.pm, lib/MIP/Recipes/Analysis/Expansionhunter.pm, lib/MIP/Recipes/Analysis/Gatk_cnnscorevariants.pm, lib/MIP/Recipes/Analysis/Gatk_variantrecalibration.pm, lib/MIP/Recipes/Analysis/Plink.pm, lib/MIP/Recipes/Analysis/Sv_combinevariantcallsets.pm
- bcftools norm behaves funny with the atomize option turned on. 
variant before norm 
```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  earlycasualcaiman   hugelymodelbat  slowlycivilbuck
1   1284490 rs150789461 G   A   779.31  PASS    AC=6;AF=1.00;AN=6;DB;DP=20;ExcessHet=3.0103;FS=0.000;MLEAC=6;MLEAF=1.00;MQ=60.00;QD=25.36;SOR=5.892;VQSLOD=11.34;culprit=MQ GT:AD:DP:GQ:PL  1/1:0,6:6:18:269,18,0   1/1:0,7:7:21:300,21,0   1/1:0,5:5:15:224,15,0
```
after norm with atomize
```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  earlycasualcaiman   hugelymodelbat  slowlycivilbuck
1   1284490 rs150789461 G   A   779.31  PASS    AC=6;AF=1;AN=6;DB=^F;DP=20;ExcessHet=3.0103;FS=0;MLEAC=6;MLEAF=1;MQ=60;QD=25.36;SOR=5.892;VQSLOD=11.34;culprit=MQ;OLD_REC_TAG=1|1284490|G|A|1 …
```
=> feat(atomize): Turns off atomize

definitions/download_parameters.yaml, lib/MIP/Cli/Mip/Download.pm, lib/MIP/Main/Download.pm, lib/MIP/Recipes/Download/Cadd_offline_annotations.pm, lib/MIP/Recipes/Download/Vcfanno_functions.pm, lib/MIP/Recipes/Pipeline/Download.pm
- The download scripts were trying to use bgzip, tabix, samtools etc but couldn't find the executables since the constants and the program executables weren't set.
=> feat(download): use containers in download

lib/MIP/Active_parameter.pm, lib/MIP/Environment/Container.pm
Previously the bind paths for an executable would be overwritten if the executable was used in more than one recipe. This appends the bind paths to the array rather than overwriting it.
=> feat(bind_paths): Don't overwrite executable bind paths

definitions/rd_dna_parameters.yaml, lib/MIP/Program/Bcftools.pm, lib/MIP/Recipes/Analysis/Glnexus.pm
- Split and normalize glnexus output 
=> feat(glnexus): split and normalize output vcf

lib/MIP/Recipes/Analysis/Mip_vcfparser.pm
The copying of mt research variants used to be part of the xargs file which could lead to the copying happening before vcfparser had finished producing the mt file. This PR moves the copying step to the main script file in order to ensure htat all files have been created prior to copying. 
=> feat(vcfparser): moved copy of mt variants

lib/MIP/Recipes/Download/Cadd_whole_genome_snvs.pm, templates/mip_download_rd_dna_config_-1.0-.yaml
- VCFanno fails to annotate SNVs with cadd scores. Regenerating the index file seems to fix the problem. Should close #1691 
=> feat(cadd_download): build cadd_snv index

lib/MIP/Program/Bcftools.pm, t/bcftools_annotate.t, t/bcftools_base.t, t/bcftools_call.t, t/bcftools_concat.t, t/bcftools_merge.t, t/bcftools_mpileup.t, t/bcftools_reheader.t, t/bcftools_roh.t, t/bcftools_sort.t
bcftools sort (version 1.10.2) uses the option name `--output-file`, while most other bcftools commands uses `--output`. This has been harmonised in more recent versions of bcftools. This pr changes the long option name for bcftools outfile path to the short option name `-o`, which is the same across bcftools command 
=> feat(bcftools_base): --output --> -o

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Glnexus.pm, templates/mip_install_config.yaml
There are still duplicate variants in the output from the glnexus recipe. This PR activates the flag `--rm-dups none` in the bcftools command of the glnexus recipe
- Run brightcaiman from the glnexus step. 
=> remove duplicates from glnexus output

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Mip_qccollect.pm, templates/mip_install_config.yaml
- Only add metric deliverables as output file for downstream use 
=> feat(store): Only add metrics deliverables to file store

definitions/rd_dna_initiation_map.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Program/Samtools.pm, lib/MIP/Recipes/Analysis/Mitodel.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm, t/analysis_mitodel.t, t/samtools_stats.t
- Adds functionality to identify mtDNA deletion signatures
=> Add mitodel recipe

CHANGELOG.md, definitions/rd_dna_parameters.yaml, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, templates/grch38_mip_rd_dna_config.yaml, templates/mip_rd_dna_config.yaml
- The haplotypecaller chain is turned off and only variants from deepvariant will be used for annotation and scoring
=> turning off haplotypecaller

lib/MIP/Recipes/Analysis/Glnexus.pm
Scout need to be able to identify the variant caller that made the call (https://github.com/Clinical-Genomics/scout/issues/2792). This PR adds the FOUND_IN tag to the info field of the vcf. This addresses #1934 
=> sed command for adding INFO tag to vcf

definitions/rd_dna_panel_parameters.yaml, definitions/rd_dna_parameters.yaml, definitions/rd_rna_parameters.yaml, lib/MIP/Cli/Mip/Qccollect.pm, lib/MIP/Main/Qccollect.pm, lib/MIP/Program/Mip.pm, lib/MIP/Recipes/Analysis/Mip_qccollect.pm, t/mip_qccollect.t, t/mip_qccollect.test
- Removes lots of info from the qc metrics file.
- Saves the qc_metrics file to deliverables
=> feat(qccollect): limit output

lib/MIP/Environment/Container.pm, t/parse_container_uri.t
- Add condition to deal with ghcr uris
=> add ghcr to parse_container_uri sub

lib/MIP/Program/HmtNote.pm, lib/MIP/Recipes/Analysis/Mt_annotation.pm, t/analysis_mt_annotation.t
- HmtNote didn't run offline because the reference to the parameter was undefined. I've updated the variable name in `Mt_annotation.pm` to match the parameter name in `rd_dna_parameters.yaml`. Additionally, the strictness of the `--offline` flag has been changed to only allow `[ 0, 1 ]`- this change is found in the `HmtNote.pm` file.
=> updated reference to the offline flag, rm'd undef for the offline flag

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Recipes/Analysis/Frequency_filter.pm, templates/mip_install_config.yaml
- https://github.com/Clinical-Genomics/MIP/issues/1944
- Added conditional to remove frequency filtering for mitochondrial vcf from `bcftools view` and instead use `gnu_cp` for them so it can still be indexed by `bcftools index`
=> added conditional to remove filtering for mitochondrial vcfs

lib/MIP/Environment/Executable.pm
- adds a regex for capturing hmtnote's version
=> adds regex for hmtnote version

lib/MIP/Program/Gnu/Software/Gnu_sed.pm, lib/MIP/Recipes/Analysis/Mt_annotation.pm, t/gnu_sed.t
- The annotations added to the info field by hmtnote contains whitespace which is a violation of the vcf spec v4.2. This sed command replaces whitespace with underscore
=> adds sed command to remove whitespace after annotation with hmtnote

CHANGELOG.md, lib/MIP/Constants.pm, lib/MIP/Store.pm, templates/mip_install_config.yaml
- Include MEDAIN_TARGET_COVERAGE in the metrics deliverable file. 
=> adds MEDIAN_TARGET_COVERAGE to deliverables

CHANGELOG.md, definitions/rd_dna_parameters.yaml, lib/MIP/Constants.pm, templates/mip_install_config.yaml
- Tiddit version 3.4.0 improves the positioning of the SV calls as well as introducing a basic scoring algorithm. The improved positioning means that we try to switch back to sv a sv annotation overlap of 0.8
#. ## How to test:
=> updates tiddit

CHANGELOG.md, definitions/rd_rna_parameters.yaml, lib/MIP/Constants.pm
- doubles the memory for salmon quant from 40 G to 80 G
=> bump memory for salmon quant

CHANGELOG.md, containers/megafusion/Dockerfile, templates/mip_install_config.yaml
- New version of MegaFusion. A bug in the previous version prevented SVDB from writing the format and sample field in the vcf.
=> updates megafusion

CHANGELOG.md, lib/MIP/Recipes/Analysis/Rseqc.pm
- This PR removes the  rseqc program that analyses read duplication as it crashes often and we already run markduplicates which will give us an idea of the duplication levels.
=> remove rseqc read duplication analysis

lib/MIP/Recipes/Analysis/Gens_generatedata.pm
- Missing `path_index` parameter, so the Gens index files are actually added to deliverables
- Check that the index files are added to deliverables
=> Adds index path to Gens deliverables

definitions/rd_dna_initiation_map.yaml, definitions/rd_dna_parameters.yaml, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, lib/MIP/Recipes/Analysis/Samtools_merge.pm, lib/MIP/Recipes/Pipeline/Analyse_rd_dna.pm
- In the WGS workflow we traditionally only operates on chromosome 1-22, X ,Y , MT but Retroseq wants to use the whole genome for calling transposable elements. This PR repurposes the panel version of `samtools_merge` to merge the files from bwa but not split them into chromosomes. 
Please ignore the wrong commit message referencing drop :p 
=> prepare bam files for retroseq

CHANGELOG.md, lib/MIP/Constants.pm, templates/mip_install_config.yaml
- Last gens patch introduced a new bug which this PR aims to fix this by updating the gens preprocessing container 
=> patching gens_preproc

CHANGELOG.md, definitions/rd_dna_parameters.yaml
- some samples requires more than 5 hours to run through retroseq. This PR increases the max run time to 15 hours.
=> increasing max retroseq run time to 15 h

CHANGELOG.md, definitions/rd_dna_parameters.yaml, lib/MIP/Main/Qccollect.pm, lib/MIP/Qccollect.pm, lib/MIP/Store.pm, t/parse_limit_qc_output.t, t/parse_sample_qc_metric.t, templates/mip_install_config.yaml, templates/qc_eval_metric_-v1.3-.yaml
- #2052 
- Filter out common SV variants using loqus and gnomad prior to converting to cytosure format.
=> Improper pair eval

CHANGELOG.md, definitions/rd_dna_panel_parameters.yaml, definitions/rd_dna_parameters.yaml, definitions/rd_rna_parameters.yaml, documentation/README.md, lib/MIP/Cli/Mip/Analyse/Rd_dna.pm, lib/MIP/Cli/Mip/Analyse/Rd_dna_panel.pm, lib/MIP/Cli/Mip/Analyse/Rd_rna.pm, lib/MIP/Qcc_regexp.pm, lib/MIP/Recipes/Analysis/Peddy.pm, lib/MIP/Recipes/Install/Mip_scripts.pm, t/data/references/qc_regexp_-v1.28-.yaml, t/mip_core.t, t/mip_qccollect.test, templates/mip_install_config.yaml, templates/qc_regexp_-v1.28-.yaml
- Capture the results from the peddy's pedigree check and fail analysis in case of mismatch with given pedigree.
- capture the results from peddy's sex check and automatically fail an analysis in the case of gender errors
=> adds automatic ped_check fail
